import { useEffect, useState } from "react";
import WI from "./WebIcons";

type ForumProps={isLoggedIn:boolean;onAuthRequired:()=>void};
const API=((import.meta.env.VITE_PLATFORM_API_URL??"") as string).replace(/\/$/,"");
const token=()=>localStorage.getItem("anpardaz:accessToken")??"";
async function api(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("content-type","application/json");const t=token();if(t)h.set("authorization","Bearer "+t);const r=await fetch(API+path,{...init,headers:h,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"خطا");return d;}
export default function WebForum({isLoggedIn,onAuthRequired}:ForumProps){
 const [rooms,setRooms]=useState<any[]>([]),[room,setRoom]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[threads,setThreads]=useState<any[]>([]),[title,setTitle]=useState(""),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 const load=async()=>{try{const [r,t]=await Promise.all([api("/api/v1/forum/rooms"),api("/api/v1/forum/threads?limit=30")]);setRooms(r.rooms??[]);setThreads(t.items??[]);}catch(e){setErr(e instanceof Error?e.message:"خطا در دریافت انجمن");}};
 useEffect(()=>{void load()},[]);
 const openRoom=async(x:any)=>{setRoom(x);try{const d=await api("/api/v1/forum/rooms/"+x.id+"/messages");setMessages(d.messages??[])}catch(e){setErr(e instanceof Error?e.message:"خطا")}};
 const openThread=async(id:number)=>{try{const d=await api("/api/v1/forum/threads/"+id);setRoom({thread:d.thread});setMessages((d.posts??[]).map((p:any)=>({...p,identity_id:p.display_name})))}catch(e){setErr(e instanceof Error?e.message:"خطا")}};
 const send=async()=>{if(!isLoggedIn){onAuthRequired();return}if(!body.trim()||busy)return;setBusy(true);setErr("");try{if(room?.thread){await api("/api/v1/forum/threads/"+room.thread.id+"/posts",{method:"POST",body:JSON.stringify({body:body.trim()})});await openThread(room.thread.id)}else if(room?.id){await api("/api/v1/forum/rooms/"+room.id+"/messages",{method:"POST",body:JSON.stringify({body:body.trim()})});await openRoom(room)}setBody("")}catch(e){setErr(e instanceof Error?e.message:"ارسال ناموفق بود")}finally{setBusy(false)}};
 const create=async()=>{if(!isLoggedIn){onAuthRequired();return}if(title.trim().length<3||busy)return;setBusy(true);try{const d=await api("/api/v1/forum/threads",{method:"POST",body:JSON.stringify({title:title.trim()})});setTitle("");await load();await openThread(d.thread.id)}catch(e){setErr(e instanceof Error?e.message:"ثبت موضوع ناموفق بود")}finally{setBusy(false)}};
 return <div className="w-fade" dir="rtl" style={{maxWidth:1100,margin:"40px auto",padding:"0 24px"}}>
  <div style={{textAlign:"center",marginBottom:30}}><h1 style={{fontSize:28,fontWeight:900,marginBottom:8}}>انجمن و گفت‌وگو</h1><p style={{color:"var(--w-muted)",fontSize:13}}>گفت‌وگوی کاربران درباره رمزارز، آموزش و اقتصاد</p></div>
  {err&&<div className="w-card" style={{padding:12,marginBottom:12,color:"#dc2626"}}>{err}</div>}
  {!room?<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>
   <section><h2 style={{fontSize:16}}>اتاق‌های گفت‌وگو</h2>{rooms.map(x=><button key={x.id} onClick={()=>void openRoom(x)} className="w-card" style={{display:"block",width:"100%",padding:16,marginBottom:10,textAlign:"right",cursor:"pointer"}}><b>{x.name}</b><div style={{fontSize:11,color:"var(--w-muted)",marginTop:5}}>{x.description}</div></button>)}</section>
   <section><h2 style={{fontSize:16}}>موضوعات انجمن</h2><div className="w-card" style={{padding:14,marginBottom:12,display:"flex",gap:8}}><input className="w-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="موضوع جدید..."/><button className="w-btn w-btn-primary" onClick={()=>void create()} disabled={busy}>ایجاد</button></div>{threads.map(x=><button key={x.id} onClick={()=>void openThread(x.id)} className="w-card" style={{display:"block",width:"100%",padding:14,marginBottom:8,textAlign:"right",cursor:"pointer"}}><b>{x.title}</b><div style={{fontSize:11,color:"var(--w-muted)",marginTop:5}}>{x.display_name??"کاربر"} · {x.updated_at??x.created_at}</div></button>)}</section>
  </div>:<section className="w-card" style={{padding:18}}><button className="w-btn w-btn-ghost" onClick={()=>setRoom(null)} style={{marginBottom:14}}><WI n="arrow-right" s={13}/> بازگشت</button><h2 style={{fontSize:18}}>{room.thread?.title??room.name}</h2><div style={{minHeight:300,maxHeight:520,overflowY:"auto",display:"grid",gap:8,margin:"16px 0"}}>{messages.slice().reverse().map((m:any)=><div key={m.id} style={{padding:11,borderRadius:10,background:"var(--w-card2)",border:"1px solid var(--w-border)"}}><div style={{fontSize:10,color:"var(--w-muted)",marginBottom:4}}>{m.display_name??m.identity_id??"کاربر"}</div><div style={{whiteSpace:"pre-wrap",lineHeight:1.8}}>{m.body}</div></div>)}</div><div style={{display:"flex",gap:8}}><textarea className="w-input" value={body} onChange={e=>setBody(e.target.value)} placeholder={isLoggedIn?"پیام خود را بنویسید...":"برای ارسال پیام وارد شوید"} rows={3}/><button className="w-btn w-btn-primary" onClick={()=>void send()} disabled={busy||!body.trim()}>ارسال</button></div></section>}
 </div>;
}