import { useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react";
import type { WebPage } from "./types";

interface Props { onNavigate: (p: WebPage) => void; }
type Tab = "home"|"assistant"|"categories"|"me";
type Product = { id:string; title:string; brand:string; description:string; specs:Record<string,unknown>; categorySlug:string; categoryName:string; images:string[]; priceMin:number; priceMax:number; storeCount:number; offerCount:number; offers:any[] };
type Category = { id:number; slug:string; name:string; name_fa:string; parent_id:number|null; icon?:string|null };

const API=((import.meta as any).env?.VITE_PLATFORM_API_URL as string|undefined)?.replace(/\/$/,"")||"";
const fa=(v:unknown)=>String(v??"").replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[Number(d)]);
const money=(v:number)=>v>0?fa(Math.round(v).toLocaleString("en-US"))+" تومان":"قیمت اعلام نشده";
const token=()=>localStorage.getItem("anpardaz:accessToken")||"";
const auth=()=>token()?{authorization:"Bearer "+token()}:{};

const css:Record<string,CSSProperties>={
  page:{minHeight:"100%",background:"var(--am-bg,#f7faf9)",color:"var(--am-text,#172033)",fontFamily:"Vazirmatn, sans-serif"},
  shell:{maxWidth:1280,margin:"0 auto",padding:"18px 20px 90px"},
  card:{background:"var(--am-card,#fff)",border:"1px solid var(--am-border,#e4ebe8)",borderRadius:18,boxShadow:"0 8px 28px rgba(15,23,42,.05)"},
  teal:{color:"#0a9e8c"},
};
function Card({children,style}:{children:ReactNode;style?:CSSProperties}){return <div style={{...css.card,...style}}>{children}</div>}
function Btn({children,onClick,active=false,primary=false,disabled=false,style}:{children:ReactNode;onClick?:()=>void;active?:boolean;primary?:boolean;disabled?:boolean;style?:CSSProperties}){return <button disabled={disabled} onClick={onClick} style={{border:"1px solid "+(primary||active?"#0a9e8c":"var(--am-border,#dfe8e4)"),background:primary?"#0a9e8c":active?"rgba(10,158,140,.09)":"var(--am-card,#fff)",color:primary?"#fff":active?"#087d70":"var(--am-text,#172033)",borderRadius:12,padding:"10px 14px",fontFamily:"Vazirmatn",fontWeight:800,cursor:disabled?"not-allowed":"pointer",opacity:disabled?.55:1,...style}}>{children}</button>}
function SearchIcon(){return <span style={{fontSize:18,color:"var(--am-muted,#64748b)"}}>⌕</span>}
function ProductCard({p,fav,onFav,onOpen,selected,onCompare}:{p:Product;fav:boolean;onFav:()=>void;onOpen:()=>void;selected:boolean;onCompare:()=>void}){return <Card style={{overflow:"hidden",display:"flex",flexDirection:"column",height:"100%"}}>
  <div onClick={onOpen} style={{position:"relative",aspectRatio:"1.08",background:"var(--am-bg,#f7faf9)",cursor:"pointer",overflow:"hidden"}}>
    {p.images[0]?<img src={p.images[0]} alt={p.title} loading="lazy" style={{width:"100%",height:"100%",objectFit:"contain"}}/>:<div style={{height:"100%",display:"grid",placeItems:"center",fontSize:40,color:"var(--am-faint,#94a3b8)"}}>▧</div>}
    <button onClick={e=>{e.stopPropagation();onFav()}} style={{position:"absolute",top:10,left:10,width:35,height:35,borderRadius:11,border:"1px solid rgba(255,255,255,.8)",background:"rgba(255,255,255,.92)",color:fav?"#db2777":"#64748b",fontSize:19,cursor:"pointer"}}>{fav?"♥":"♡"}</button>
    <button onClick={e=>{e.stopPropagation();onCompare()}} style={{position:"absolute",top:10,right:10,border:0,background:selected?"#0a9e8c":"rgba(255,255,255,.94)",color:selected?"#fff":"#334155",borderRadius:10,padding:"6px 9px",fontFamily:"Vazirmatn",fontWeight:800,fontSize:10,cursor:"pointer"}}>{selected?"✓ انتخاب شد":"مقایسه"}</button>
  </div>
  <div style={{padding:14,display:"flex",flexDirection:"column",gap:6,flex:1}}>
    <div style={{fontSize:11,...css.teal,fontWeight:800}}>{p.brand||p.categoryName}</div>
    <div onClick={onOpen} style={{fontSize:14,fontWeight:900,lineHeight:1.7,cursor:"pointer"}}>{p.title}</div>
    <div style={{fontSize:11,color:"var(--am-muted,#64748b)"}}>{fa(p.storeCount)} فروشگاه · {fa(p.offerCount)} پیشنهاد</div>
    <div style={{marginTop:"auto",fontSize:15,fontWeight:900,...css.teal}}>{money(p.priceMin)}</div>
  </div>
</Card>}

function ProductDetail({p,onBack,fav,onFav}:{p:Product;onBack:()=>void;fav:boolean;onFav:()=>void}){
 const [offers,setOffers]=useState<any[]>(p.offers||[]),[frame,setFrame]=useState(""),[ai,setAi]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(offers.length)return;void fetch(API+"/api/v1/market/products/"+p.id).then(r=>r.ok?r.json():null).then(d=>d&&setOffers(d.offers||[])).catch(()=>{})},[p.id,offers.length]);
 useEffect(()=>{if(token())void fetch(API+"/api/v1/market/products/"+p.id+"/view",{method:"POST",headers:{"content-type":"application/json",...auth()},body:JSON.stringify({surface:"web"})})},[p.id]);
 const click=async(o:any)=>{try{const r=await fetch(API+"/api/v1/market/clickout",{method:"POST",headers:{"content-type":"application/json",...auth()},body:JSON.stringify({offerId:Number(o.id),surface:"web"})});const d=await r.json();if(!r.ok)throw 0;if(d.mode==="iframe")setFrame(d.url);else window.open(d.url,"_blank","noopener,noreferrer")}catch{}};
 const ask=async()=>{if(!ai.trim()||!token())return;setBusy(true);try{const r=await fetch(API+"/api/v1/market/ai/assist",{method:"POST",headers:{"content-type":"application/json",...auth()},body:JSON.stringify({workflowCode:"market.assist",input:ai.trim(),productId:p.id})});const d=await r.json();window.alert(d.output?.text||d.output||"پاسخی دریافت نشد.")}finally{setBusy(false)}};
 return <div style={css.page} dir="rtl"><div style={css.shell}>
   <div style={{display:"flex",justifyContent:"space-between",gap:10,marginBottom:14}}><Btn onClick={onBack}>‹ بازگشت</Btn><Btn onClick={onFav}>{fav?"♥ حذف از علاقه‌مندی":"♡ علاقه‌مندی"}</Btn></div>
   <Card style={{overflow:"hidden"}}>
    <div style={{display:"grid",gridTemplateColumns:"minmax(300px,1fr) minmax(360px,1fr)"}}>
      <div style={{background:"var(--am-bg,#f7faf9)",minHeight:420,display:"grid",placeItems:"center"}}>{p.images[0]?<img src={p.images[0]} alt={p.title} style={{width:"100%",height:"100%",maxHeight:520,objectFit:"contain"}}/>:<span style={{color:"var(--am-muted)"}}>تصویر موجود نیست</span>}</div>
      <div style={{padding:26}}><div style={{...css.teal,fontWeight:800,fontSize:12}}>{p.brand||p.categoryName}</div><h1 style={{fontSize:24,lineHeight:1.6,margin:"7px 0 12px"}}>{p.title}</h1><p style={{color:"var(--am-muted,#64748b)",lineHeight:2,fontSize:13}}>{p.description||"توضیحات محصول از منبع واقعی فروشگاه دریافت نشده است."}</p>
       <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,margin:"18px 0"}}>{[["پایین‌ترین قیمت",money(p.priceMin)],["بالاترین قیمت",money(p.priceMax)],["فروشگاه‌ها",fa(p.storeCount)]].map(([a,b])=><div key={a} style={{padding:12,borderRadius:12,background:"var(--am-bg,#f7faf9)",border:"1px solid var(--am-border,#e4ebe8)"}}><div style={{fontSize:10,color:"var(--am-muted)"}}>{a}</div><b style={{display:"block",marginTop:5,fontSize:12}}>{b}</b></div>)}</div>
       <div style={{display:"flex",gap:8}}><input value={ai} onChange={e=>setAi(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void ask()} placeholder="از دستیار درباره این محصول بپرس…" style={{flex:1,minWidth:0,padding:"11px 13px",borderRadius:12,border:"1px solid var(--am-border,#dfe8e4)",fontFamily:"Vazirmatn",direction:"rtl"}}/><Btn primary disabled={busy||!token()} onClick={()=>void ask()}>{busy?"…":"از دستیار بپرس"}</Btn></div>
      </div>
    </div>
    <div style={{padding:"20px 24px 28px"}}><h3 style={{marginTop:0}}>فروشگاه‌ها و قیمت‌های واقعی</h3>{offers.length===0?<div style={{padding:22,color:"var(--am-muted)"}}>هنوز پیشنهاد فروشگاهی واقعی برای این محصول ثبت نشده است.</div>:offers.map(o=><div key={o.id} style={{display:"flex",alignItems:"center",gap:12,padding:"13px 0",borderBottom:"1px solid var(--am-border,#e4ebe8)"}}><div style={{flex:1}}><b>{o.store_name||"فروشگاه"}</b><div style={{fontSize:11,color:"var(--am-muted)",marginTop:3}}>{o.availability==="out_of_stock"?"ناموجود":"موجود"} · {o.store_domain||""}</div></div><strong>{money(Number(o.price||0))}</strong><Btn onClick={()=>void click(o)}>{o.iframe_mode==="allowed"?"مشاهده داخل آن مارکت":"ورود به فروشگاه"}</Btn></div>)}</div>
   </Card>
 </div>{frame&&<div onClick={()=>setFrame("")} style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(2,6,23,.72)",padding:"4vh 4vw"}}><div onClick={e=>e.stopPropagation()} style={{height:"92vh",background:"#fff",borderRadius:18,overflow:"hidden"}}><div style={{height:48,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 14px"}}><b>فروشگاه</b><Btn onClick={()=>setFrame("")}>بستن</Btn></div><iframe src={frame} title="فروشگاه" style={{width:"100%",height:"calc(100% - 48px)",border:0}}/></div></div>}</div>
}

export default function WebMarket({onNavigate:_onNavigate}:Props){
 const [tab,setTab]=useState<Tab>("home"),[products,setProducts]=useState<Product[]>([]),[cats,setCats]=useState<Category[]>([]),[q,setQ]=useState(""),[search,setSearch]=useState(""),[cat,setCat]=useState("all"),[selected,setSelected]=useState<Product|null>(null),[favorites,setFavorites]=useState<Set<string>>(new Set()),[compare,setCompare]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[ticket,setTicket]=useState(""),[tickets,setTickets]=useState<any[]>([]);
 const load=async()=>{setLoading(true);try{const url=API+"/api/v1/market/catalog?limit=100"+(search?"&q="+encodeURIComponent(search):"")+(cat!=="all"?"&category="+encodeURIComponent(cat):"");const r=await fetch(url);if(!r.ok)throw 0;const d=await r.json();setProducts((d.products||[]).map((p:any)=>({id:String(p.id),title:p.title||"",brand:p.brand||"",description:p.description||"",specs:p.specs||{},categorySlug:p.category_slug||"",categoryName:p.category_name_fa||p.category_name||"",images:(p.media||[]).map((m:any)=>m.url).filter(Boolean).concat((p.offers||[]).map((o:any)=>o.image_url).filter(Boolean)).slice(0,8),priceMin:Number(p.priceMin||0),priceMax:Number(p.priceMax||0),storeCount:Number(p.storeCount||0),offerCount:Number(p.offerCount||0),offers:p.offers||[]})));setError("")}catch{setProducts([]);setError("اطلاعات واقعی آن مارکت در دسترس نیست.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[search,cat]);
 useEffect(()=>{void (async()=>{try{const c=await fetch(API+"/api/v1/market/categories");if(c.ok)setCats((await c.json()).categories||[]);if(token()){const f=await fetch(API+"/api/v1/market/me/favorites",{headers:auth()});if(f.ok)setFavorites(new Set(((await f.json()).products||[]).map((x:any)=>String(x.id))))}}catch{}})()},[]);
 useEffect(()=>{if(tab==="me"&&token())void fetch(API+"/api/v1/market/me/tickets",{headers:auth()}).then(r=>r.ok?r.json():null).then(d=>d&&setTickets(d.tickets||[]))},[tab]);
 const roots=cats.filter(c=>!c.parent_id);
 const visible=useMemo(()=>products,[products]);
 const toggleFav=async(id:string)=>{if(!token())return;const r=await fetch(API+"/api/v1/market/products/"+id+"/favorite",{method:"POST",headers:auth()});if(r.ok){const d=await r.json();setFavorites(s=>{const n=new Set(s);d.favorite?n.add(id):n.delete(id);return n})}};
 const compareToggle=(id:string)=>setCompare(x=>x.includes(id)?x.filter(i=>i!==id):x.length<6?[...x,id]:x);
 if(selected)return <ProductDetail p={selected} onBack={()=>setSelected(null)} fav={favorites.has(selected.id)} onFav={()=>void toggleFav(selected.id)}/>;
 const tabBtn=(t:Tab,label:string)=><button onClick={()=>setTab(t)} style={{flex:1,padding:"10px 8px",borderRadius:12,border:"1px solid "+(tab===t?"#0a9e8c":"var(--am-border,#e4ebe8)"),background:tab===t?"rgba(10,158,140,.09)":"var(--am-card,#fff)",color:tab===t?"#087d70":"var(--am-muted,#64748b)",fontFamily:"Vazirmatn",fontWeight:900,cursor:"pointer"}}>{label}</button>;
 return <div style={css.page} dir="rtl"><div style={css.shell}>
   <div style={{background:"var(--am-card,#fff)",borderBottom:"1px solid var(--am-border,#e4ebe8)",padding:"18px 0 16px",marginBottom:14,boxShadow:"0 2px 12px rgba(10,25,41,.05)"}}>
    <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:14}}><div style={{width:44,height:44,borderRadius:14,background:"#0a9e8c",display:"grid",placeItems:"center",boxShadow:"0 4px 16px rgba(10,158,140,.28)"}}><span style={{color:"#fff",fontSize:22}}>⌂</span></div><div style={{flex:1}}><div style={{fontSize:20,fontWeight:950}}>آن مارکت</div><div style={{fontSize:11,color:"var(--am-muted,#64748b)",marginTop:3}}>مقایسه قیمت از صدها فروشگاه معتبر</div></div><div style={{fontSize:11,fontWeight:800,color:"#087d70",background:"rgba(10,158,140,.08)",padding:"9px 12px",borderRadius:12}}>{fa(roots.length)} دسته اصلی</div></div>
    <div style={{display:"flex",gap:8,alignItems:"center",padding:4,border:"1.5px solid rgba(100,140,180,.22)",borderRadius:18,boxShadow:"0 2px 12px rgba(10,25,41,.08)"}}><SearchIcon/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setSearch(q.trim())} placeholder="جستجو در بیش از ۱ میلیون محصول…" style={{flex:1,border:0,outline:0,background:"transparent",fontFamily:"Vazirmatn",fontSize:13}}/><Btn primary onClick={()=>setSearch(q.trim())}>جستجو</Btn></div>
   </div>
   <div style={{...css.card,padding:8,display:"flex",gap:8,marginBottom:12}}><SearchIcon/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setSearch(q.trim())} placeholder="جستجو در محصولات واقعی…" style={{flex:1,border:0,outline:0;background:"transparent",fontFamily:"Vazirmatn",fontSize:13}}/><Btn primary onClick={()=>setSearch(q.trim())}>جستجو</Btn></div>
   <div style={{display:"flex",gap:7,marginBottom:16}}>{tabBtn("home","خانه")}{tabBtn("assistant","دستیار هوشمند")}{tabBtn("categories","دسته‌بندی‌ها")}{tabBtn("me","آن مارکت من")}</div>
   {tab==="home"&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:8,marginBottom:18}}>{roots.slice(0,12).map(c=><button key={c.id} onClick={()=>setCat(c.slug)} style={{textAlign:"right",padding:"12px 13px",borderRadius:14,border:"1px solid var(--am-border,#e4ebe8)",background:"var(--am-card,#fff)",fontFamily:"Vazirmatn",cursor:"pointer"}}><div style={{fontWeight:850,fontSize:12}}>{c.name_fa}</div><div style={{fontSize:10,color:"var(--am-muted)",marginTop:4}}>مشاهده محصولات</div></button>)}</div>
     <button onClick={()=>setTab("assistant")} style={{display:"flex",alignItems:"center",gap:8,width:"100%",marginBottom:14,padding:"11px 18px",background:compare.length>0?"linear-gradient(135deg,#92400e,#b45309)":"linear-gradient(135deg,rgba(180,83,9,.06),rgba(217,119,6,.04))",border:"1.8px solid rgba(180,83,9,.35)",borderRadius:14,cursor:"pointer",fontFamily:"Vazirmatn",color:compare.length>0?"#fff":"#92400e",fontSize:13,fontWeight:800,boxShadow:"0 0 10px rgba(180,83,9,.12)"}}>
       <span>▦</span><span>{compare.length>0?"مقایسه فعال است":"مقایسه کن"}</span>{compare.length>0&&<span style={{marginRight:"auto",background:"rgba(255,255,255,.2)",borderRadius:8,padding:"2px 8px",fontSize:11}}>{fa(compare.length)} محصول</span>}<span style={{width:9,height:9,borderRadius:"50%",background:"#d97706"}}/>
     </button>
     {loading?<Card style={{padding:50,textAlign:"center",color:"var(--am-muted)"}}>در حال دریافت محصولات واقعی…</Card>:error?<Card style={{padding:50,textAlign:"center",color:"#dc2626"}}>{error}</Card>:visible.length===0?<Card style={{padding:50,textAlign:"center",color:"var(--am-muted)"}}>هنوز محصول واقعی در دیتابیس آن مارکت ثبت نشده است؛ بعد از راه‌اندازی اتصال فروشگاه‌ها این بخش خودکار پر می‌شود.</Card>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(205px,1fr))",gap:13}}>{visible.map(p=><ProductCard key={p.id} p={p} fav={favorites.has(p.id)} onFav={()=>void toggleFav(p.id)} onOpen={()=>setSelected(p)} selected={compare.includes(p.id)} onCompare={()=>compareToggle(p.id)}/>)}</div>}
   </>}
   {tab==="assistant"&&<Card style={{padding:22,maxWidth:860,margin:"0 auto"}}><div style={{fontSize:20,fontWeight:950,marginBottom:8}}>دستیار هوشمند آن مارکت</div><p style={{fontSize:12,color:"var(--am-muted)",lineHeight:2}}>پاسخ‌ها باید فقط بر پایه اطلاعات واقعی محصولات و پیشنهادهای ثبت‌شده در آن مارکت باشند.</p><textarea id="market-ai" placeholder="مثلاً برای یک لپ‌تاپ مناسب برنامه‌نویسی چه گزینه‌هایی دارم؟" style={{width:"100%",minHeight:150,boxSizing:"border-box",padding:14,borderRadius:14,border:"1px solid var(--am-border,#e4ebe8)",fontFamily:"Vazirmatn",direction:"rtl"}}/><Btn primary onClick={async()=>{const el=document.getElementById("market-ai") as HTMLTextAreaElement|null;const input=el?.value.trim();if(!input||!token())return;const r=await fetch(API+"/api/v1/market/ai/assist",{method:"POST",headers:{"content-type":"application/json",...auth()},body:JSON.stringify({workflowCode:compare.length>1?"market.compare":"market.assist",input,compareIds:compare})});const d=await r.json();window.alert(d.output?.text||d.output||"پاسخی دریافت نشد.")}} style={{marginTop:10}}>ارسال به دستیار</Btn></Card>}
   {tab==="categories"&&<div style={{display:"grid",gap:10}}>{roots.map(c=><Card key={c.id} style={{padding:15,cursor:"pointer"}}><button onClick={()=>setCat(c.slug)} style={{width:"100%",border:0,background:"none",textAlign:"right",fontFamily:"Vazirmatn",cursor:"pointer"}}><div style={{fontWeight:850}}>{c.name_fa}</div><div style={{fontSize:11,color:"var(--am-muted)",marginTop:4}}>مشاهده محصولات این دسته</div></button></Card>)}</div>}
   {tab==="me"&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:10}}>{[["علاقه‌مندی‌ها",fa(favorites.size)+" محصول"],["مقایسه‌های من",fa(compare.length)+" انتخاب فعلی"],["تیکت‌های پشتیبانی",fa(tickets.length)+" تیکت"]].map(([a,b])=><Card key={a} style={{padding:17}}><div style={{fontWeight:900}}>{a}</div><div style={{fontSize:12,color:"var(--am-muted)",marginTop:7}}>{b}</div></Card>)}<Card style={{padding:17}}><div style={{fontWeight:900,marginBottom:9}}>ثبت تیکت جدید</div><textarea value={ticket} onChange={e=>setTicket(e.target.value)} placeholder="شرح مشکل یا سؤال" style={{width:"100%",minHeight:100,boxSizing:"border-box",padding:11,borderRadius:11,border:"1px solid var(--am-border,#e4ebe8)",fontFamily:"Vazirmatn"}}/><Btn primary onClick={async()=>{if(!token()||!ticket.trim())return;const r=await fetch(API+"/api/v1/market/tickets",{method:"POST",headers:{"content-type":"application/json",...auth()},body:JSON.stringify({subject:"پشتیبانی آن مارکت",message:ticket.trim()})});if(r.ok){setTicket("");const d=await fetch(API+"/api/v1/market/me/tickets",{headers:auth()});if(d.ok)setTickets((await d.json()).tickets||[])}}} style={{marginTop:9}}>ثبت تیکت</Btn></Card></div>}
 </div></div>
}
