import { useEffect, useState, type CSSProperties, type ReactNode } from "react";

type AdminUser={email:string;role:string};
type Json=Record<string,any>;

const API=(import.meta as any).env?.VITE_PLATFORM_API_URL??"";
const fa=(v:unknown)=>String(v??"").replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[+d]);
const money=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n.toLocaleString("fa-IR"):"—"};

async function api(path:string,token:string,init:RequestInit={}){
  const r=await fetch(API+path,{...init,headers:{...(init.headers??{}),authorization:"Bearer "+token,"content-type":"application/json"}});
  const text=await r.text();let body:any={};try{body=text?JSON.parse(text):{}}catch{body={error:"invalid_response"}}
  if(!r.ok)throw new Error(body?.error??("HTTP "+r.status));
  return body;
}

function Card({children,style}:{children:ReactNode;style?:CSSProperties}){return <div className="w-card" style={{padding:18,...style}}>{children}</div>}
function Badge({children,tone="muted"}:{children:ReactNode;tone?:string}){const colors:any={ok:"#059669",bad:"#dc2626",warn:"#d97706",muted:"var(--w-muted)",blue:"#0891b2"};return <span style={{display:"inline-flex",padding:"4px 9px",borderRadius:20,fontSize:11,fontWeight:800,background:"var(--w-card2)",color:colors[tone]??colors.muted}}>{children}</span>}

export default function AdminPanel(){
  const [token,setToken]=useState(()=>sessionStorage.getItem("anpardaz_admin_token")??"");
  const [user,setUser]=useState<AdminUser|null>(null);
  const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [loginError,setLoginError]=useState("");
  const [tab,setTab]=useState<"overview"|"trace"|"kyc"|"withdrawals"|"funding"|"forexbot"|"user"|"market"|"hoosh"|"financial"|"anpardaz"|"sayad">("overview");
  const [overview,setOverview]=useState<Json|null>(null);const [health,setHealth]=useState<Json|null>(null);
  const [op,setOp]=useState("");const [identity,setIdentity]=useState("");const [userSummary,setUserSummary]=useState<Json|null>(null);const [trace,setTrace]=useState<Json|null>(null);const [traceError,setTraceError]=useState("");
  const [kyc,setKyc]=useState<any[]>([]);const [kycStatus,setKycStatus]=useState("");
  const [withdrawals,setWithdrawals]=useState<any[]>([]);const [wdStatus,setWdStatus]=useState("");const [supportTickets,setSupportTickets]=useState<any[]>([]);const [supportTicket,setSupportTicket]=useState<any|null>(null);const [supportReply,setSupportReply]=useState("");const [anpardazOps,setAnpardazOps]=useState<any[]>([]);const [bankingOps,setBankingOps]=useState<any[]>([]);const [anpardazOp,setAnpardazOp]=useState("");const [anpardazTrace,setAnpardazTrace]=useState<Json|null>(null);
  const [bannerOverview,setBannerOverview]=useState<any|null>(null);const [bannerAlerts,setBannerAlerts]=useState<any[]>([]);const [bannerTemplates,setBannerTemplates]=useState<any[]>([]);const [bannerUserId,setBannerUserId]=useState("");const [bannerUserSummary,setBannerUserSummary]=useState<any|null>(null);const [bannerListings,setBannerListings]=useState<any[]>([]);const [bannerTickets,setBannerTickets]=useState<any[]>([]);const [bannerReports,setBannerReports]=useState<any[]>([]);const [bannerTicket,setBannerTicket]=useState<any|null>(null);const [bannerReply,setBannerReply]=useState("");const [bannerActivity,setBannerActivity]=useState<any[]>([]);const [bannerAudit,setBannerAudit]=useState<any[]>([]);
    const [forexRequests,setForexRequests]=useState<any[]>([]);const [forexStatus,setForexStatus]=useState("");
  const [ansarrafFees,setAnsarrafFees]=useState<any[]>([]);const [feeForm,setFeeForm]=useState({operationType:"withdrawal",assetSymbol:"",marketSymbol:"",percentage:"0",fixedAmount:"0",minAmount:"",maxAmount:"",feeAssetSymbol:""});
  const [fundingCard,setFundingCard]=useState("");const [fundingIdentity,setFundingIdentity]=useState("");const [fundingAmount,setFundingAmount]=useState("");const [fundingReference,setFundingReference]=useState("");const [manualDeposits,setManualDeposits]=useState<any[]>([]);const [financialUserId,setFinancialUserId]=useState("");const [financialData,setFinancialData]=useState<any|null>(null);const [cardLifecycle,setCardLifecycle]=useState<any|null>(null);const [cardLookupNumber,setCardLookupNumber]=useState("");const [cardLookupData,setCardLookupData]=useState<any|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [hooshOverview,setHooshOverview]=useState<Json|null>(null);const [hooshRequests,setHooshRequests]=useState<any[]>([]);const [hooshTickets,setHooshTickets]=useState<any[]>([]);const [hooshTicket,setHooshTicket]=useState<any|null>(null);const [hooshReply,setHooshReply]=useState("");const [marketReport,setMarketReport]=useState<Json|null>(null);const [marketCategories,setMarketCategories]=useState<any[]>([]);const [marketActivity,setMarketActivity]=useState<any[]>([]);const [marketAIHistory,setMarketAIHistory]=useState<any[]>([]);const [marketTicket,setMarketTicket]=useState<any|null>(null);const [marketTicketReply,setMarketTicketReply]=useState("");const [sayadOps,setSayadOps]=useState<any[]>([]);const [sayadStatus,setSayadStatus]=useState("");const [marketStores,setMarketStores]=useState<any[]>([]);const [marketTickets,setMarketTickets]=useState<any[]>([]);const [marketEvents,setMarketEvents]=useState<any[]>([]);const [marketSources,setMarketSources]=useState<any[]>([]);const [marketRuns,setMarketRuns]=useState<any[]>([]);const [contentPolicies,setContentPolicies]=useState<any[]>([]);const [contentPipeline,setContentPipeline]=useState<any|null>(null);const [contentVideos,setContentVideos]=useState<any[]>([]);const [contentDaily,setContentDaily]=useState("5");const [contentVideoTitle,setContentVideoTitle]=useState("");const [contentVideoCategory,setContentVideoCategory]=useState("video-news");const [contentVideoFile,setContentVideoFile]=useState<File|null>(null);const [contentAutoPublish,setContentAutoPublish]=useState(false);const [contentRequireReview,setContentRequireReview]=useState(true);

  const logout=()=>{sessionStorage.removeItem("anpardaz_admin_token");setToken("");setUser(null);};
  const load=async(t:string)=>{
    setBusy(true);setError("");
    try{
      const me=await api("/api/v1/auth/me",t);const role=me?.user?.role;
      if(!["admin","super_admin","operator","support"].includes(role))throw new Error("admin_access_required");
      setUser({email:me.user.email,role});
      const [o,h]=await Promise.all([api("/api/v1/admin/overview",t),api("/api/v1/admin/ecosystem/health",t).catch((e)=>({error:e.message}))]);
      setOverview(o);setHealth(h);
    }catch(e){setError(e instanceof Error?e.message:"خطا");logout()}finally{setBusy(false)}
  };
  useEffect(()=>{if(token)void load(token)},[token]);
  useEffect(()=>{if(token&&tab==="ansarraf-fees")void loadAnsarrafFees()},[token,tab]);

  const login=async()=>{
    setBusy(true);setLoginError("");
    try{
      const x=await api("/api/v1/auth/login","", {method:"POST",body:JSON.stringify({email,password})});sessionStorage.setItem("anpardaz_admin_token",x.accessToken);setToken(x.accessToken)
    }catch(e){setLoginError(e instanceof Error?e.message:"ورود ناموفق بود")}finally{setBusy(false)}
  };
  const loadContent=async()=>{setBusy(true);try{const [p,pipe,v]=await Promise.all([api("/api/v1/admin/content/policies",token),api("/api/v1/admin/content/pipeline",token),api("/api/v1/admin/content/videos",token)]);setContentPolicies(p.policies??[]);setContentPipeline(pipe);setContentVideos(v.videos??[]);}catch(e){setError(e instanceof Error?e.message:"content_admin_failed")}finally{setBusy(false)}};
  const uploadContentVideo=async()=>{if(!contentVideoTitle.trim()||!contentVideoFile)return;setBusy(true);try{const fd=new FormData();fd.append("title",contentVideoTitle.trim());fd.append("category",contentVideoCategory);fd.append("file",contentVideoFile);const base=(import.meta.env.VITE_PLATFORM_API_URL??"").replace(/\/$/,"");const r=await fetch(base+"/api/v1/admin/content/videos",{method:"POST",headers:{authorization:"Bearer "+token},body:fd});if(!r.ok)throw new Error("video_upload_failed");setContentVideoTitle("");setContentVideoFile(null);await loadContent()}catch(e){setError(e instanceof Error?e.message:"video_upload_failed")}finally{setBusy(false)}};
  const updateContentPolicy=async(category:string)=>{setBusy(true);try{await api("/api/v1/admin/content/policies/"+encodeURIComponent(category),token,{method:"PUT",body:JSON.stringify({dailyLimit:Number(contentDaily),autoPublish:contentAutoPublish,requireReview:contentRequireReview})});await loadContent()}catch(e){setError(e instanceof Error?e.message:"content_policy_failed")}finally{setBusy(false)}};
  const loadAnsarrafFees=async()=>{setBusy(true);try{const x=await api("/api/v1/admin/ecosystem/ansarraf/fees",token);setAnsarrafFees(x.rules??[])}catch(e){setError(e instanceof Error?e.message:"ansarraf_fees_failed")}finally{setBusy(false)}};
  const saveAnsarrafFee=async()=>{setBusy(true);setError("");try{await api("/api/v1/admin/ecosystem/ansarraf/fees",token,{method:"POST",body:JSON.stringify({operationType:feeForm.operationType,assetSymbol:feeForm.assetSymbol||null,marketSymbol:feeForm.marketSymbol||null,percentage:feeForm.percentage||"0",fixedAmount:feeForm.fixedAmount||"0",minAmount:feeForm.minAmount||null,maxAmount:feeForm.maxAmount||null,feeAssetSymbol:feeForm.feeAssetSymbol||feeForm.assetSymbol||null})});await loadAnsarrafFees()}catch(e){setError(e instanceof Error?e.message:"ansarraf_fee_save_failed")}finally{setBusy(false)}};
  const closeAnsarrafFee=async(id:number)=>{setBusy(true);try{await api("/api/v1/admin/ecosystem/ansarraf/fees/"+id+"/close",token,{method:"POST",body:"{}"});await loadAnsarrafFees()}catch(e){setError(e instanceof Error?e.message:"ansarraf_fee_close_failed")}finally{setBusy(false)}};
  const loadForexRequests=async()=>{setBusy(true);try{const x=await api("/api/v1/admin/ecosystem/ansarraf/forex-bot/requests"+(forexStatus?"?status="+encodeURIComponent(forexStatus):""),token);setForexRequests(x.requests??[])}catch(e){setError(e instanceof Error?e.message:"forex_bot_admin_failed")}finally{setBusy(false)}};
  const decideForex=async(id:number,approve:boolean)=>{const reason=window.prompt(approve?"دلیل تأیید را وارد کنید":"دلیل رد را وارد کنید");if(reason===null)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/ansarraf/forex-bot/requests/"+id+"/decision",token,{method:"POST",body:JSON.stringify({approve,reason})});await loadForexRequests()}catch(e){setError(e instanceof Error?e.message:"forex_bot_decision_failed")}finally{setBusy(false)}};
  
  const loadManualDeposits=async()=>{setBusy(true);try{const x=await api("/api/v1/admin/ecosystem/ansarraf/deposits/manual",token);setManualDeposits(x.deposits??[])}catch(e){setError(e instanceof Error?e.message:"manual_deposits_failed")}finally{setBusy(false)}};
  const creditManualToman=async()=>{if(!fundingCard||!fundingIdentity||!fundingAmount||!fundingReference)return;setBusy(true);setError("");try{await api("/api/v1/admin/ecosystem/ansarraf/deposits/manual/credit",token,{method:"POST",body:JSON.stringify({cardNumber:fundingCard,identityId:fundingIdentity,amount:fundingAmount,externalReference:fundingReference})});setFundingReference("");await loadManualDeposits()}catch(e){setError(e instanceof Error?e.message:"manual_toman_credit_failed")}finally{setBusy(false)}};
  const loadFinancial=async()=>{if(!financialUserId.trim())return;setBusy(true);setError("");try{const [financial,lifecycle]=await Promise.all([api("/api/v1/admin/ecosystem/anpardaz/financial-center/"+encodeURIComponent(financialUserId.trim()),token),api("/api/v1/admin/ecosystem/anpardaz/cards/lifecycle/"+encodeURIComponent(financialUserId.trim()),token)]);setFinancialData(financial);setCardLifecycle(lifecycle)}catch(e){setError(e instanceof Error?e.message:"financial_lookup_failed")}finally{setBusy(false)}};
  const exportFinancial=()=>{if(!financialData?.csv)return;const blob=new Blob([financialData.csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="anpardaz-financial-center-"+financialUserId.trim()+".csv";a.click();URL.revokeObjectURL(url)};
  const lookupCard=async()=>{const card=cardLookupNumber.replace(/\\s/g,"");if(!/^\\d{16}$/.test(card)){setError("شماره کارت باید ۱۶ رقمی باشد.");return}setBusy(true);setError("");try{setCardLookupData(await api("/api/v1/admin/ecosystem/anpardaz/cards/lookup?cardNumber="+encodeURIComponent(card),token))}catch(e){setCardLookupData(null);setError(e instanceof Error?e.message:"card_lookup_failed")}finally{setBusy(false)}};
  const loadUser=async()=>{if(!identity.trim())return;setBusy(true);try{setUserSummary(await api("/api/v1/admin/ecosystem/users/"+encodeURIComponent(identity.trim()),token))}catch(e){setError(e instanceof Error?e.message:"user_lookup_failed")}finally{setBusy(false)}};
  const loadTrace=async()=>{if(!op.trim())return;setBusy(true);setTraceError("");try{setTrace(await api("/api/v1/admin/ecosystem/operations/"+encodeURIComponent(op.trim())+"/trace",token))}catch(e){setTrace(null);setTraceError(e instanceof Error?e.message:"trace_failed")}finally{setBusy(false)}};
  const loadSupport=async()=>{setBusy(true);try{const x=await api("/api/v1/admin/support/tickets",token);setSupportTickets(x.tickets??[]);}catch(e){setError(e instanceof Error?e.message:"support_failed")}finally{setBusy(false)}};
const loadSupportTicket=async(id:number)=>{setBusy(true);try{const x=await api("/api/v1/admin/support/tickets/"+id,token);setSupportTicket(x);}catch(e){setError(e instanceof Error?e.message:"support_ticket_failed")}finally{setBusy(false)}};
const replySupport=async()=>{if(!supportTicket?.ticket?.id||!supportReply.trim())return;setBusy(true);try{await api("/api/v1/admin/support/tickets/"+supportTicket.ticket.id+"/reply",token,{method:"POST",body:JSON.stringify({message:supportReply.trim()})});setSupportReply("");await loadSupportTicket(Number(supportTicket.ticket.id));}catch(e){setError(e instanceof Error?e.message:"support_reply_failed")}finally{setBusy(false)}};
const closeSupport=async()=>{if(!supportTicket?.ticket?.id)return;setBusy(true);try{await api("/api/v1/admin/support/tickets/"+supportTicket.ticket.id+"/close",token,{method:"POST",body:"{}"});await loadSupportTicket(Number(supportTicket.ticket.id));await loadSupport();}catch(e){setError(e instanceof Error?e.message:"support_close_failed")}finally{setBusy(false)}};
const loadKyc=async()=>{setBusy(true);try{const x=await api("/api/v1/admin/ecosystem/ansarraf/kyc"+(kycStatus?"?status="+encodeURIComponent(kycStatus):""),token);setKyc(x.kyc??[])}catch(e){setError(e instanceof Error?e.message:"kyc_failed")}finally{setBusy(false)}};
  const decideKyc=async(id:number,approve:boolean)=>{const reason=window.prompt(approve?"دلیل تأیید را وارد کنید":"دلیل رد را وارد کنید");if(reason===null)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/ansarraf/kyc/"+id+"/decision",token,{method:"POST",body:JSON.stringify({approve,reason})});await loadKyc()}catch(e){setError(e instanceof Error?e.message:"kyc_decision_failed")}finally{setBusy(false)}};
  const loadSayad=async()=>{setBusy(true);try{const x=await api("/api/v1/admin/ecosystem/anpardaz/sayad-operations"+(sayadStatus?"?status="+encodeURIComponent(sayadStatus):""),token);setSayadOps(x.operations??[])}catch(e){setError(e instanceof Error?e.message:"sayad_operations_failed")}finally{setBusy(false)}};
  const loadAnpardaz=async()=>{setBusy(true);try{const [x,b]=await Promise.all([api("/api/v1/admin/ecosystem/anpardaz/operations",token),api("/api/v1/admin/ecosystem/anpardaz/banking-operations",token)]);setAnpardazOps(x.operations??[]);setBankingOps(b.operations??[])}catch(e){setError(e instanceof Error?e.message:"anpardaz_operations_failed")}finally{setBusy(false)}};
  const loadAnpardazTrace=async()=>{if(!anpardazOp.trim())return;setBusy(true);try{setAnpardazTrace(await api("/api/v1/admin/ecosystem/anpardaz/operations/"+encodeURIComponent(anpardazOp.trim()),token))}catch(e){setError(e instanceof Error?e.message:"anpardaz_trace_failed")}finally{setBusy(false)}};
  const completeToman=async(id:number)=>{const reference=window.prompt("شناسه پرداخت/رسید بانکی را وارد کنید");if(!reference)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/ansarraf/withdrawals/"+id+"/complete-toman",token,{method:"POST",body:JSON.stringify({payoutReference:reference})});await loadWd()}catch(e){setError(e instanceof Error?e.message:"toman_payout_failed")}finally{setBusy(false)}};
  const loadWd=async()=>{setBusy(true);try{const x=await api("/api/v1/admin/ecosystem/ansarraf/withdrawals"+(wdStatus?"?status="+encodeURIComponent(wdStatus):""),token);setWithdrawals(x.withdrawals??[])}catch(e){setError(e instanceof Error?e.message:"withdrawals_failed")}finally{setBusy(false)}};
  const approveWd=async(id:number)=>{setBusy(true);try{await api("/api/v1/admin/ecosystem/ansarraf/withdrawals/"+id+"/approve",token,{method:"POST",body:"{}"});await loadWd()}catch(e){setError(e instanceof Error?e.message:"approval_failed")}finally{setBusy(false)}};
  const rejectWd=async(id:number)=>{const reason=window.prompt("دلیل رد برداشت");if(reason===null)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/ansarraf/withdrawals/"+id+"/reject",token,{method:"POST",body:JSON.stringify({reason})});await loadWd()}catch(e){setError(e instanceof Error?e.message:"reject_failed")}finally{setBusy(false)}};
  const reconcileWd=async(id:number)=>{const providerWithdrawalId=window.prompt("Provider Withdrawal ID (اگر موجود است)");if(!providerWithdrawalId)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/ansarraf/withdrawals/"+id+"/reconcile",token,{method:"POST",body:JSON.stringify({providerWithdrawalId})});await loadWd()}catch(e){setError(e instanceof Error?e.message:"reconcile_failed")}finally{setBusy(false)}};
  const loadHoosh=async()=>{setBusy(true);try{const [o,r,t]=await Promise.all([api("/api/v1/admin/hoosh/overview",token),api("/api/v1/admin/hoosh/requests",token),api("/api/v1/admin/hoosh/tickets",token)]);setHooshOverview(o);setHooshRequests(r.requests??[]);setHooshTickets(t.tickets??[])}catch(e){setError(e instanceof Error?e.message:"hoosh_admin_failed")}finally{setBusy(false)}}; const loadHooshTicket=async(id:number)=>{try{setHooshTicket(await api("/api/v1/admin/hoosh/tickets/"+id,token))}catch(e){setError(e instanceof Error?e.message:"hoosh_ticket_failed")}}; const replyHoosh=async()=>{if(!hooshTicket?.ticket?.id||!hooshReply.trim())return;setBusy(true);try{await api("/api/v1/admin/hoosh/tickets/"+hooshTicket.ticket.id+"/reply",token,{method:"POST",body:JSON.stringify({content:hooshReply})});setHooshReply("");await loadHooshTicket(hooshTicket.ticket.id);await loadHoosh()}catch(e){setError(e instanceof Error?e.message:"hoosh_ticket_reply_failed")}finally{setBusy(false)}}; const updateHooshTicket=async(status:string)=>{if(!hooshTicket?.ticket?.id)return;setBusy(true);try{await api("/api/v1/admin/hoosh/tickets/"+hooshTicket.ticket.id,token,{method:"PATCH",body:JSON.stringify({status})});await loadHooshTicket(hooshTicket.ticket.id);await loadHoosh()}catch(e){setError(e instanceof Error?e.message:"hoosh_ticket_update_failed")}finally{setBusy(false)}};
  const loadBannerUser=async()=>{if(!bannerUserId.trim())return;setBusy(true);try{setBannerUserSummary(await api("/api/v1/admin/ecosystem/banner/users/"+encodeURIComponent(bannerUserId.trim()),token))}catch(e){setError(e instanceof Error?e.message:"banner_user_lookup_failed")}finally{setBusy(false)}};
  const loadBanner=async()=>{setBusy(true);try{const [o,l,t,rp,a,au,al,tm]=await Promise.all([api("/api/v1/admin/ecosystem/banner/overview",token),api("/api/v1/admin/ecosystem/banner/listings?limit=200",token),api("/api/v1/admin/ecosystem/banner/tickets?limit=200",token),api("/api/v1/admin/ecosystem/banner/reports?limit=200",token),api("/api/v1/admin/ecosystem/banner/activity?limit=500",token),api("/api/v1/admin/ecosystem/banner/audit?limit=500",token),api("/api/v1/admin/ecosystem/banner/alerts?limit=100",token),api("/api/v1/admin/ecosystem/banner/templates",token)]);setBannerOverview(o);setBannerAlerts(al.alerts??[]);setBannerTemplates(tm.templates??[]);setBannerListings(l.listings??[]);setBannerTickets(t.tickets??[]);setBannerReports(rp.reports??[]);setBannerActivity(a.activities??[]);setBannerAudit(au.audit??[])}catch(e){setError(e instanceof Error?e.message:"banner_admin_failed")}finally{setBusy(false)}};
  const loadBannerTicket=async(id:number)=>{try{setBannerTicket(await api("/api/v1/admin/ecosystem/banner/tickets/"+id,token))}catch(e){setError(e instanceof Error?e.message:"banner_ticket_failed")}};
  const replyBannerTicket=async()=>{if(!bannerTicket?.ticket?.id||!bannerReply.trim())return;setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/tickets/"+bannerTicket.ticket.id+"/reply",token,{method:"POST",body:JSON.stringify({message:bannerReply.trim()})});setBannerReply("");await loadBannerTicket(bannerTicket.ticket.id);await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_ticket_reply_failed")}finally{setBusy(false)}};
  const updateBannerTicket=async(status:string)=>{if(!bannerTicket?.ticket?.id)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/tickets/"+bannerTicket.ticket.id,token,{method:"PATCH",body:JSON.stringify({status})});await loadBannerTicket(bannerTicket.ticket.id);await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_ticket_update_failed")}finally{setBusy(false)}};
  const updateBannerReport=async(id:number,status:string)=>{setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/reports/"+id,token,{method:"PATCH",body:JSON.stringify({status})});await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_report_update_failed")}finally{setBusy(false)}};
   const exportBannerUserHistory=async()=>{if(!bannerUserId.trim())return;try{const res=await fetch(API+"/api/v1/admin/ecosystem/banner/users/"+encodeURIComponent(bannerUserId.trim())+"/export?format=csv",{headers:{authorization:"Bearer "+token}});if(!res.ok)throw new Error("export_failed");const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="an-banner-user-history.csv";a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"export_failed")}};
   const editBannerTemplate=async(t:any)=>{const title=window.prompt("عنوان پیام",t.title);if(title===null)return;const body=window.prompt("متن پیام",t.body);if(body===null)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/templates/"+t.id,token,{method:"PATCH",body:JSON.stringify({title,body,restrictionCode:t.restriction_code,durationHours:t.duration_hours,active:t.active})});await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_template_update_failed")}finally{setBusy(false)}};
   const sendBannerUserMessage=async(templateId?:number)=>{if(!bannerUserId.trim())return;const template=templateId?bannerTemplates.find(x=>x.id===templateId):null;const body=template?{templateId}:{};setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/users/"+encodeURIComponent(bannerUserId.trim())+"/message",token,{method:"POST",body:JSON.stringify(body)});await loadBannerUser();await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_message_failed")}finally{setBusy(false)}};
   const restrictBannerUser=async(code:string)=>{if(!bannerUserId.trim())return;const reason=window.prompt("دلیل محدودیت");if(reason===null)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/users/"+encodeURIComponent(bannerUserId.trim())+"/restrict",token,{method:"POST",body:JSON.stringify({restrictionCode:code,reason,durationHours:24})});await loadBannerUser();await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_restrict_failed")}finally{setBusy(false)}};
   const unrestrictBannerUser=async()=>{if(!bannerUserId.trim())return;setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/users/"+encodeURIComponent(bannerUserId.trim())+"/unrestrict",token,{method:"POST",body:JSON.stringify({})});await loadBannerUser();await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_unrestrict_failed")}finally{setBusy(false)}};
   const banBannerUser=async()=>{if(!bannerUserId.trim())return;const reason=window.prompt("دلیل مسدودسازی دائمی");if(reason===null)return;setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/users/"+encodeURIComponent(bannerUserId.trim())+"/ban",token,{method:"POST",body:JSON.stringify({reason})});await loadBannerUser();await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_ban_failed")}finally{setBusy(false)}};
   const updateBannerListing=async(id:number,status:string)=>{setBusy(true);try{await api("/api/v1/admin/ecosystem/banner/listings/"+id+"/status",token,{method:"PATCH",body:JSON.stringify({status})});await loadBanner()}catch(e){setError(e instanceof Error?e.message:"banner_listing_update_failed")}finally{setBusy(false)}};
  const loadMarket=async()=>{setBusy(true);try{const [s,t,e,src,runs,report,cats,activity,aih]=await Promise.all([api("/api/v1/admin/market/stores",token),api("/api/v1/admin/market/tickets",token),api("/api/v1/admin/market/events",token),api("/api/v1/admin/market/sources",token),api("/api/v1/admin/market/sync-runs",token),api("/api/v1/admin/market/merchant-report",token),api("/api/v1/admin/market/categories",token),api("/api/v1/admin/market/activity?limit=500",token),api("/api/v1/admin/market/ai-history?limit=200",token)]);setMarketStores(s.stores??[]);setMarketTickets(t.tickets??[]);setMarketEvents(e.events??[]);setMarketSources(src.sources??[]);setMarketRuns(runs.runs??[]);setMarketReport(report);setMarketCategories(cats.categories??[]);setMarketActivity(activity.activities??[]);setMarketAIHistory(aih.conversations??[])}catch(e){setError(e instanceof Error?e.message:"market_admin_failed")}finally{setBusy(false)}};
  const loadMarketTicket=async(id:number)=>{try{const d=await api("/api/v1/admin/market/tickets/"+id,token);setMarketTicket(d)}catch(e){setError(e instanceof Error?e.message:"market_ticket_failed")}};
  const replyMarketTicket=async()=>{if(!marketTicket?.ticket?.id||!marketTicketReply.trim())return;setBusy(true);try{await api("/api/v1/admin/market/tickets/"+marketTicket.ticket.id+"/reply",token,{method:"POST",body:JSON.stringify({message:marketTicketReply.trim()})});setMarketTicketReply("");await loadMarketTicket(marketTicket.ticket.id);await loadMarket()}catch(e){setError(e instanceof Error?e.message:"market_ticket_reply_failed")}finally{setBusy(false)}};
  const updateMarketTicket=async(status:string)=>{if(!marketTicket?.ticket?.id)return;setBusy(true);try{await api("/api/v1/admin/market/tickets/"+marketTicket.ticket.id,token,{method:"PATCH",body:JSON.stringify({status})});await loadMarketTicket(marketTicket.ticket.id);await loadMarket()}catch(e){setError(e instanceof Error?e.message:"market_ticket_update_failed")}finally{setBusy(false)}};
  const exportMarketActivity=async()=>{try{const r=await fetch(API+"/api/v1/admin/market/export/activity.csv",{headers:{authorization:"Bearer "+token}});if(!r.ok)throw new Error("export_failed");const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="an-market-activity.csv";a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"export_failed")}};
  const exportMarketReport=async()=>{try{const r=await fetch(API+"/api/v1/admin/market/merchant-report.csv",{headers:{authorization:"Bearer "+token}});if(!r.ok)throw new Error("export_failed");const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="an-market-merchant-report.csv";a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"export_failed")}};


  if(!token||!user)return <div dir="rtl" style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"var(--w-bg)"}}><Card style={{width:"100%",maxWidth:430}}><div style={{textAlign:"center",marginBottom:24}}><div style={{fontSize:24,fontWeight:900}}>پنل مدیریت آن پرداز</div><div style={{fontSize:12,color:"var(--w-muted)",marginTop:6}}>دسترسی عملیاتی، حسابداری و Trace</div></div><input className="w-input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ایمیل مدیر" dir="ltr" style={{marginBottom:10}}/><input className="w-input" value={password} onChange={e=>setPassword(e.target.value)} placeholder="رمز عبور" type="password" dir="ltr" onKeyDown={e=>e.key==="Enter"&&login()}/>{loginError&&<div style={{color:"#dc2626",fontSize:12,marginTop:8}}>{loginError}</div>}<button className="w-btn w-btn-primary" onClick={login} disabled={busy||!email||!password} style={{width:"100%",marginTop:16,padding:12}}>{busy?"در حال ورود…":"ورود به پنل مدیریت"}</button></Card></div>;

  const tabs=[["overview","داشبورد"],["user","کاربر / Wallet / Orders"],["financial","مرکز مالی"],["anpardaz","آن پرداز"],["sayad","چک صیادی"],["trace","Operation Trace"],["kyc","احراز هویت آن صراف"],["withdrawals","برداشت‌ها"],["funding","شارژ دستی تومان"],["ansarraf-fees","کارمزد آن صراف"],["forexbot","ربات فارکس"],["market","آن مارکت"],["banner","آن بنر"],["hoosh","آن هوش"],["content","اخبار / محتوا / ویدئو"],["support","پشتیبانی آن پرداز"]];
  return <div dir="rtl" style={{minHeight:"100vh",background:"var(--w-bg)",padding:"28px 24px 60px"}}>
    <div style={{maxWidth:1400,margin:"0 auto"}}>
      <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,marginBottom:22}}>
        <div><div style={{fontSize:25,fontWeight:900}}>مرکز کنترل آن پرداز</div><div style={{fontSize:12,color:"var(--w-muted)",marginTop:4}}>حسابداری، آن صراف، سلامت سرویس‌ها و Trace یکپارچه</div></div>
        <div style={{display:"flex",alignItems:"center",gap:10}}><Badge tone="blue">{user.role}</Badge><span style={{fontSize:12,color:"var(--w-muted)"}}>{user.email}</span><button className="w-btn w-btn-ghost" onClick={logout}>خروج</button></div>
      </header>
      <div style={{display:"flex",gap:7,flexWrap:"wrap",marginBottom:18}}>{tabs.map(([id,label])=><button key={id} className={tab===id?"w-btn w-btn-primary":"w-btn w-btn-ghost"} onClick={()=>{setTab(id as any);if(id==="kyc")void loadKyc();if(id==="withdrawals")void loadWd();if(id==="anpardaz")void loadAnpardaz();if(id==="sayad")void loadSayad();if(id==="market")void loadMarket();if(id==="banner")void loadBanner();if(id==="hoosh")void loadHoosh();if(id==="funding")void loadManualDeposits();if(id==="forexbot")void loadForexRequests();if(id==="content")void loadContent();if(id==="support")void loadSupport()}}>{label}</button>)}</div>
      {error&&<Card style={{marginBottom:14,borderColor:"rgba(220,38,38,.25)",color:"#dc2626"}}>{error}</Card>}
{tab==="anpardaz"&&<><Card><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={{fontWeight:900,fontSize:17}}>عملیات خدمات آن پرداز</div><div style={{fontSize:12,color:"var(--w-muted)",marginTop:5,lineHeight:1.8}}>وضعیت واقعی سرویس، Provider، خطا و وضعیت حسابداری از Backend خوانده می‌شود.</div></div><button className="w-btn w-btn-primary" onClick={()=>void loadAnpardaz()}>بروزرسانی</button></div></Card><Card style={{marginTop:14,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Operation","Service","Status","Provider","Provider Ref","Accounting","Created"].map(h=><th key={h} style={{padding:9,textAlign:"right",borderBottom:"1px solid var(--w-border)"}}>{h}</th>)}</tr></thead><tbody>{anpardazOps.map((x:any)=><tr key={x.operation_id}><td dir="ltr" style={{padding:9}}>{x.operation_id}</td><td style={{padding:9}}>{x.service_code}</td><td style={{padding:9}}><Badge tone={x.status==="completed"?"ok":x.status==="failed"?"bad":x.status==="manual_review"?"warn":"blue"}>{x.status}</Badge></td><td style={{padding:9}}>{x.provider_code??"—"}</td><td dir="ltr" style={{padding:9}}>{x.external_reference??x.provider_operation_id??"—"}</td><td style={{padding:9}}>{x.accounting_status??"—"}</td><td style={{padding:9}}>{x.created_at?new Date(x.created_at).toLocaleString("fa-IR"):"—"}</td></tr>)}</tbody></table>{anpardazOps.length===0&&<div style={{padding:20,textAlign:"center",color:"var(--w-muted)"}}>عملیاتی ثبت نشده است.</div>}</Card><Card style={{marginTop:14}}><div style={{fontWeight:900,marginBottom:10}}>Trace عملیات</div><div style={{display:"flex",gap:8}}><input className="w-input" value={anpardazOp} onChange={e=>setAnpardazOp(e.target.value)} placeholder="Operation ID" dir="ltr"/><button className="w-btn w-btn-ghost" onClick={()=>void loadAnpardazTrace()}>مشاهده</button></div>{anpardazTrace&&<pre style={{marginTop:12,whiteSpace:"pre-wrap",overflow:"auto",fontSize:11}}>{JSON.stringify(anpardazTrace,null,2)}</pre>}</Card></>}
{tab==="sayad"&&<><Card><div style={{display:"flex",gap:8}}><select className="w-input" value={sayadStatus} onChange={e=>setSayadStatus(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="pending">pending</option><option value="processing">processing</option><option value="completed">completed</option><option value="failed">failed</option><option value="manual_review">manual_review</option></select><button className="w-btn w-btn-primary" onClick={()=>void loadSayad()}>بروزرسانی</button></div></Card><Card style={{marginTop:14,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Operation","Service","Status","Provider","Reference","Accounting"].map(h=><th key={h} style={{padding:9,textAlign:"right",borderBottom:"1px solid var(--w-border)"}}>{h}</th>)}</tr></thead><tbody>{sayadOps.map((x:any)=><tr key={x.operation_id}><td dir="ltr" style={{padding:9}}>{x.operation_id}</td><td style={{padding:9}}>{x.service_code}</td><td style={{padding:9}}>{x.status}</td><td style={{padding:9}}>{x.provider_code??"—"}</td><td dir="ltr" style={{padding:9}}>{x.external_reference??"—"}</td><td style={{padding:9}}>{x.accounting_status??"—"}</td></tr>)}</tbody></table></Card></>}
{tab==="forexbot"&&<><Card><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:900,fontSize:17}}>مدیریت ربات فارکس آن صراف</div><div style={{fontSize:12,color:"var(--w-muted)",marginTop:4}}>حداکثر سرمایه اولیه هر کاربر ۳۰ USDT؛ فعال‌سازی و غیرفعال‌سازی فقط با تصمیم مدیر.</div></div><button className="w-btn w-btn-primary" onClick={()=>void loadForexRequests()}>بروزرسانی</button></div></Card><Card style={{marginTop:14,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["ID","کاربر","درخواست","مبلغ","ربات","P&L","عملیات"].map(h=><th key={h} style={{padding:9,textAlign:"right",borderBottom:"1px solid var(--w-border)"}}>{h}</th>)}</tr></thead><tbody>{forexRequests.map((x:any)=><tr key={x.id}><td>{x.id}</td><td dir="ltr">{x.email??x.identity_id??"—"}</td><td>{x.action==="activate"?"فعال‌سازی":"غیرفعال‌سازی"} · {x.status}</td><td dir="ltr">{x.requested_amount??"—"} USDT</td><td>{x.bot_status}</td><td dir="ltr">{x.total_pnl??"0"} USDT</td><td>{x.status==="pending"&&<div style={{display:"flex",gap:5}}><button className="w-btn w-btn-primary" onClick={()=>void decideForex(Number(x.id),true)}>تأیید</button><button className="w-btn w-btn-ghost" onClick={()=>void decideForex(Number(x.id),false)}>رد</button></div>}</td></tr>)}</tbody></table></Card></>}
{tab==="kyc"&&<><Card><div style={{display:"flex",gap:8,alignItems:"center"}}><select className="w-input" value={kycStatus} onChange={e=>setKycStatus(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="ADMIN_REVIEW">ADMIN_REVIEW</option><option value="VERIFIED">VERIFIED</option><option value="REJECTED">REJECTED</option><option value="PROVIDER_REJECTED">PROVIDER_REJECTED</option><option value="REQUIRES_ACTION">REQUIRES_ACTION</option></select><button className="w-btn w-btn-primary" onClick={loadKyc}>بروزرسانی</button></div></Card><Card style={{marginTop:14,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["ID","کاربر","وضعیت","Provider","Identity Match","Mobile Match","عملیات"].map(h=><th key={h} style={{padding:10,textAlign:"right",borderBottom:"1px solid var(--w-border)"}}>{h}</th>)}</tr></thead><tbody>{kyc.map((x:any)=><tr key={x.id}>{[x.id,x.email,x.status,x.provider_code,x.provider_identity_match?"بله":"خیر",x.provider_mobile_match?"بله":"خیر"].map((v:any,i:number)=><td key={i} style={{padding:10,borderBottom:"1px solid var(--w-border)"}}>{String(v??"—")}</td>)}<td style={{padding:10}}><div style={{display:"flex",gap:5}}>{x.status==="ADMIN_REVIEW"&&<><button className="w-btn w-btn-primary" onClick={()=>decideKyc(x.id,true)}>تأیید</button><button className="w-btn w-btn-ghost" onClick={()=>decideKyc(x.id,false)}>رد</button></>}</div></td></tr>)}</tbody></table></Card></>}
      {tab==="ansarraf-fees"&&<><Card><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:900,fontSize:17}}>تنظیم کارمزدهای آن صراف</div><div style={{fontSize:12,color:"var(--w-muted)",marginTop:5}}>نرخ‌های واریز، برداشت، انتقال و معامله مستقیماً در Backend ذخیره می‌شوند و بعد از تغییر، موبایل و وب آن را از API می‌خوانند.</div></div><button className="w-btn w-btn-ghost" onClick={loadAnsarrafFees}>بروزرسانی</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:14}}>
<select className="w-input" value={feeForm.operationType} onChange={e=>setFeeForm({...feeForm,operationType:e.target.value})}><option value="trade">معامله</option><option value="deposit">واریز</option><option value="withdrawal">برداشت</option><option value="transfer">انتقال</option></select>
<input className="w-input" value={feeForm.assetSymbol} onChange={e=>setFeeForm({...feeForm,assetSymbol:e.target.value.toUpperCase()})} placeholder="دارایی مثل USDT"/>
<input className="w-input" value={feeForm.marketSymbol} onChange={e=>setFeeForm({...feeForm,marketSymbol:e.target.value.toUpperCase()})} placeholder="بازار اختیاری مثل BTC/USDT"/>
<input className="w-input" value={feeForm.percentage} onChange={e=>setFeeForm({...feeForm,percentage:e.target.value})} placeholder="درصد به صورت اعشاری مثل 0.005" dir="ltr"/>
<input className="w-input" value={feeForm.fixedAmount} onChange={e=>setFeeForm({...feeForm,fixedAmount:e.target.value})} placeholder="کارمزد ثابت" dir="ltr"/>
<input className="w-input" value={feeForm.minAmount} onChange={e=>setFeeForm({...feeForm,minAmount:e.target.value})} placeholder="حداقل کارمزد" dir="ltr"/>
<input className="w-input" value={feeForm.maxAmount} onChange={e=>setFeeForm({...feeForm,maxAmount:e.target.value})} placeholder="حداکثر کارمزد" dir="ltr"/>
<input className="w-input" value={feeForm.feeAssetSymbol} onChange={e=>setFeeForm({...feeForm,feeAssetSymbol:e.target.value.toUpperCase()})} placeholder="ارز دریافت کارمزد"/>
</div><button className="w-btn w-btn-primary" style={{marginTop:10}} onClick={saveAnsarrafFee} disabled={busy}>ثبت قانون جدید</button></Card><Card style={{marginTop:14,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["عملیات","دارایی","بازار","درصد","ثابت","حداقل","حداکثر","ارز کارمزد","اعتبار","عملیات"].map(h=><th key={h} style={{padding:9,textAlign:"right",borderBottom:"1px solid var(--w-border)"}}>{h}</th>)}</tr></thead><tbody>{ansarrafFees.map((x:any)=><tr key={x.id}><td style={{padding:9}}>{x.operation_type}</td><td style={{padding:9}}>{x.asset_symbol??"همه"}</td><td style={{padding:9}}>{x.market_symbol??"همه"}</td><td style={{padding:9}} dir="ltr">{x.percentage}</td><td style={{padding:9}} dir="ltr">{x.fixed_amount}</td><td style={{padding:9}} dir="ltr">{x.min_amount??"—"}</td><td style={{padding:9}} dir="ltr">{x.max_amount??"—"}</td><td style={{padding:9}}>{x.fee_asset_symbol??"—"}</td><td style={{padding:9}} dir="ltr">{x.effective_from} → {x.effective_to??"فعال"}</td><td style={{padding:9}}>{!x.effective_to&&<button className="w-btn w-btn-ghost" onClick={()=>closeAnsarrafFee(Number(x.id))}>بستن</button>}</td></tr>)}</tbody></table></Card></>}

      {tab==="funding"&&<><Card><div style={{fontWeight:900,fontSize:17}}>شارژ دستی حساب تومان آن صراف</div><div style={{fontSize:12,color:"var(--w-muted)",marginTop:5,lineHeight:1.8}}>ابتدا شماره کارت پرداخت‌کننده با کارت تأییدشده آن پرداز تطبیق می‌شود؛ سپس سند دوطرفه حسابداری و موجودی کاربر ثبت می‌گردد.</div><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8,marginTop:14}}><input className="w-input" value={fundingCard} onChange={e=>setFundingCard(e.target.value)} placeholder="شماره کارت پرداخت‌کننده" dir="ltr"/><input className="w-input" value={fundingIdentity} onChange={e=>setFundingIdentity(e.target.value)} placeholder="Identity ID کاربر" dir="ltr"/><input className="w-input" value={fundingAmount} onChange={e=>setFundingAmount(e.target.value)} placeholder="مبلغ تومان" inputMode="decimal" dir="ltr"/><input className="w-input" value={fundingReference} onChange={e=>setFundingReference(e.target.value)} placeholder="شناسه یکتای واریز/صورتحساب" dir="ltr"/></div><div style={{display:"flex",gap:8,marginTop:10}}><button className="w-btn w-btn-primary" onClick={creditManualToman} disabled={busy||!fundingCard||!fundingIdentity||!fundingAmount||!fundingReference}>تطبیق کارت و شارژ حساب</button><button className="w-btn w-btn-ghost" onClick={loadManualDeposits}>بروزرسانی</button></div></Card><Card style={{marginTop:14,overflow:"auto"}}><div style={{fontWeight:900,marginBottom:10}}>سوابق شارژ دستی</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["ID","کاربر","کارت","مبلغ","وضعیت","مرجع","Accounting Operation","مدیر"].map(h=><th key={h} style={{padding:9,textAlign:"right",borderBottom:"1px solid var(--w-border)"}}>{h}</th>)}</tr></thead><tbody>{manualDeposits.map((x:any)=><tr key={x.id}><td style={{padding:9}}>{x.id}</td><td style={{padding:9}}>{x.identity_id??"—"}</td><td style={{padding:9}}>•••• {x.source_card_last4??"—"}</td><td style={{padding:9}}>{money(x.amount)} {x.asset_symbol}</td><td style={{padding:9}}>{x.status}</td><td dir="ltr" style={{padding:9}}>{x.external_reference}</td><td dir="ltr" style={{padding:9}}>{x.accounting_operation_id??"—"}</td><td style={{padding:9}}>{x.admin_actor_identity_id??"—"}</td></tr>)}</tbody></table></Card></>}
{tab==="withdrawals"&&<><Card><div style={{display:"flex",gap:8}}><select className="w-input" value={wdStatus} onChange={e=>setWdStatus(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="pending">pending</option><option value="processing">processing</option><option value="completed">completed</option><option value="cancelled">cancelled</option></select><button className="w-btn w-btn-primary" onClick={loadWd}>بروزرسانی</button></div></Card><Card style={{marginTop:14,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["ID","Operation","Asset","Amount","Approval","Status","Provider","عملیات"].map(h=><th key={h} style={{padding:10,textAlign:"right",borderBottom:"1px solid var(--w-border)"}}>{h}</th>)}</tr></thead><tbody>{withdrawals.map((x:any)=><tr key={x.id}>{[x.id,x.operation_id,x.symbol,money(x.amount),x.approval_status,x.status,x.provider_code??"—"].map((v:any,i:number)=><td key={i} dir={i===1?"ltr":"rtl"} style={{padding:10,borderBottom:"1px solid var(--w-border)"}}>{String(v??"—")}</td>)}<td style={{padding:10}}><div style={{display:"flex",gap:5}}>{x.approval_status==="PENDING"&&x.status==="pending"&&<><button className="w-btn w-btn-primary" onClick={()=>approveWd(x.id)}>تأیید</button><button className="w-btn w-btn-ghost" onClick={()=>rejectWd(x.id)}>رد</button></>}{x.approval_status==="APPROVED"&&x.status==="processing"&&(x.symbol==="TMN"||x.symbol==="IRT"||x.symbol==="IRR")&&<button className="w-btn w-btn-primary" onClick={()=>completeToman(x.id)}>ثبت پرداخت تومان</button>}{x.approval_status==="APPROVED"&&x.status==="processing"&&!(x.symbol==="TMN"||x.symbol==="IRT"||x.symbol==="IRR")&&<button className="w-btn w-btn-ghost" onClick={()=>reconcileWd(x.id)}>Reconcile</button>}</div></td></tr>)}</tbody></table></Card></>}
    </div>
  </div>;
}
