import type {LiquidityProviderAdapter,ProviderBalance,ProviderOrderRequest,ProviderOrderResult,ProviderOrderStatus,ProviderWithdrawalRequest,ProviderWithdrawalResult} from './types.js';

type WallexConfig={baseUrl:string;apiKey:string;timeoutMs:number};
const asText=(v:unknown)=>v===undefined||v===null?'0':String(v);
const wallexSymbol=(symbol:string)=>{const normalized=symbol.toUpperCase();return normalized.endsWith("/TOMAN")?normalized.slice(0,-6)+"/TMN":normalized;};
const status=(value:any):ProviderOrderStatus=>{const s=String(value??'').toUpperCase();if(['FILLED','DONE','COMPLETED'].includes(s))return 'FILLED';if(['PARTIALLY_FILLED','PARTIAL'].includes(s))return 'PARTIALLY_FILLED';if(['CANCELED','CANCELLED'].includes(s))return 'CANCELLED';if(['REJECTED','FAILED'].includes(s))return 'REJECTED';if(['NEW','OPEN','ACTIVE','PENDING','PARTIALLY_FILLED_PENDING'].includes(s))return 'SUBMITTED';return 'UNKNOWN';};

export class WallexAdapter implements LiquidityProviderAdapter{
 readonly code='WALLEX';
 constructor(private readonly cfg:WallexConfig){if(!cfg.baseUrl||!cfg.apiKey)throw new Error('wallex_provider_not_configured');}
 private async request(path:string,init:RequestInit={}){const response=await fetch(this.cfg.baseUrl.replace(/\/$/,'')+path,{...init,headers:{accept:'application/json','content-type':'application/json','x-api-key':this.cfg.apiKey,...(init.headers??{})},signal:AbortSignal.timeout(this.cfg.timeoutMs)});let body:any={};try{body=await response.json();}catch{}if(!response.ok)throw new Error('wallex_http_'+response.status+':'+JSON.stringify(body).slice(0,1000));return body;}
 async getOrderBook(symbol:string){const body=await this.request('/v1/depth?symbol='+encodeURIComponent(wallexSymbol(symbol)));const data=body?.result??body?.data??body;const normalize=(rows:any[])=>rows.map((x:any)=>Array.isArray(x)?[asText(x[0]),asText(x[1])] as [string,string]:[asText(x?.price),asText(x?.quantity)] as [string,string]).filter((x:[string,string])=>x[0]!=='0'&&x[1]!=='0');return {bids:normalize(data?.bid??data?.bids??[]),asks:normalize(data?.ask??data?.asks??[]),raw:body};}
 async getBalances():Promise<ProviderBalance[]>{const body=await this.request('/v1/account/balances');const data=body?.result?.balances??body?.result??body?.data??body;const rows=Array.isArray(data)?data:Object.values(data??{});return rows.map((x:any)=>({asset:String(x.asset??x.symbol??''),available:asText(x.value??x.available??x.free),locked:asText(x.locked??x.lockedAmount),raw:x}));}
 async submitOrder(request:ProviderOrderRequest):Promise<ProviderOrderResult>{const body=await this.request('/v1/account/orders',{method:'POST',body:JSON.stringify({symbol:wallexSymbol(request.symbol),type:request.orderType.toUpperCase(),side:request.side.toUpperCase(),quantity:request.quantity,...(request.price?{price:request.price}:{}),client_id:request.clientOrderId})});return this.mapOrder(body,request.clientOrderId);}
 async getOrder(clientOrderId:string,_providerOrderId?:string|null):Promise<ProviderOrderResult>{return this.mapOrder(await this.request('/v1/account/orders/'+encodeURIComponent(clientOrderId)),clientOrderId);}
 async cancelOrder(clientOrderId:string,_providerOrderId?:string|null):Promise<ProviderOrderResult>{return this.mapOrder(await this.request('/v1/account/orders?clientOrderId='+encodeURIComponent(clientOrderId),{method:'DELETE'}),clientOrderId);}
 async getDepositAddress(asset:string,network:string){
   const body=await this.request('/v1/account/wallets/'+encodeURIComponent(asset.toLowerCase())+'?network='+encodeURIComponent(network.toLowerCase()));
   const x=body?.result??body?.data??body;
   const wallets=Array.isArray(x?.wallets)?x.wallets:Object.values(x?.wallets??{});
   const selected=(wallets as any[]).find((w:any)=>String(w?.network?.name??w?.network??'').toLowerCase()===network.toLowerCase())??(wallets as any[])[0]??x;
   return {asset:asset.toUpperCase(),network,address:String(selected?.address??selected?.wallet_address??x?.address??''),memo:selected?.memo??selected?.tag??null,raw:body};
 }
 async listDeposits(page=1,perPage=100){
   const body=await this.request('/v1/account/crypto-deposit?page='+page+'&per_page='+perPage);
   const rows=Array.isArray(body?.result)?body.result:(body?.result?.deposits??body?.data??[]);
   return rows.map((x:any)=>({providerEventId:String(x?.id??x?.txHash??x?.tx_hash??(String(x?.asset??'')+'|'+String(x?.amount??'')+'|'+String(x?.time??''))),asset:String(x?.asset??x?.coin?.key??'').toUpperCase(),network:x?.network?.name?String(x.network.name):x?.network?String(x.network):null,amount:asText(x?.amount??x?.value),address:x?.wallet?.address??x?.address??null,memo:x?.wallet?.memo??x?.memo??null,txHash:x?.txHash??x?.tx_hash??null,confirmations:Number(x?.confirmations??0),requiredConfirmations:Number(x?.min_confirmation??x?.network?.min_confirmation??1),status:String(x?.status??'UNKNOWN'),raw:x}));
 }
 async submitWithdrawal(request:ProviderWithdrawalRequest):Promise<ProviderWithdrawalResult>{return this.mapWithdrawal(await this.request('/v1/account/crypto-withdrawal',{method:'POST',body:JSON.stringify({coin:request.asset,network:request.network,value:request.amount,wallet_address:request.destination,...(request.memo?{memo:request.memo}:{})})}));}
 async getWithdrawal(providerWithdrawalId:string):Promise<ProviderWithdrawalResult>{const body=await this.request('/v1/account/crypto-withdrawal?page=1&per_page=100');const rows=Array.isArray(body?.result)?body.result:(body?.result?.withdrawals??body?.data??[]);const found=rows.find((x:any)=>String(x?.id??'')===String(providerWithdrawalId));return found?this.mapWithdrawal({success:true,result:found}):{providerWithdrawalId,status:'UNKNOWN',amount:'0',feeAmount:'0',txHash:null,raw:body};}
 private mapWithdrawal(body:any):ProviderWithdrawalResult{const x=body?.result??body?.data??body;const s=String(x?.status??'').toUpperCase();return {providerWithdrawalId:x?.id!==undefined?String(x.id):null,status:['ACCOMPLISHED','COMPLETED','CONFIRMED','SUCCESS'].includes(s)?'COMPLETED':['PENDING','PROCESSING','IN_PROGRESS'].includes(s)?'PROCESSING':['FAILED','REJECTED','CANCELLED','CANCELED'].includes(s)?'FAILED':'UNKNOWN',amount:asText(x?.amount??x?.value),feeAmount:asText(x?.fee),txHash:x?.txHash?String(x.txHash):null,raw:body};}
 private mapOrder(body:any,clientOrderId:string):ProviderOrderResult{const x=body?.result??body?.data??body;const fills=Array.isArray(x?.fills)?x.fills:[];const fee=x?.fee!==undefined?x.fee:fills.reduce((sum:any,fill:any)=>sum+Number(fill?.fee??0),0);const feeAsset=x?.feeAsset??fills.find((fill:any)=>fill?.feeAsset)?.feeAsset??null;return {providerOrderId:x?.orderId!==undefined?String(x.orderId):x?.id!==undefined?String(x.id):x?.clientOrderId?String(x.clientOrderId):null,clientOrderId:String(x?.clientOrderId??clientOrderId),status:status(x?.status),executedQuantity:asText(x?.executedQty),executedQuoteAmount:asText(x?.executedSum),providerFeeAmount:asText(fee),providerFeeAssetSymbol:feeAsset?String(feeAsset):null,raw:body};}
}
