import { createHash, createPrivateKey, createPublicKey, randomBytes, randomUUID, randomInt, scrypt as scryptCallback, sign as signData, timingSafeEqual, verify as verifyData } from 'node:crypto';
import { promisify } from 'node:util';
import type { FastifyRequest, FastifyReply } from 'fastify';
import type { Pool } from 'pg';
const scrypt=promisify(scryptCallback); const PRIVATE_KEY_B64=process.env.IDENTITY_PRIVATE_KEY_B64;
if(!PRIVATE_KEY_B64)throw new Error('IDENTITY_PRIVATE_KEY_B64 must be configured');
const privateKey=createPrivateKey({key:Buffer.from(PRIVATE_KEY_B64,'base64'),format:'der',type:'pkcs8'}); const publicKey=createPublicKey(privateKey); const TOKEN_TTL_SECONDS=3600; const issuer=()=>process.env.IDENTITY_ISSUER??'anpardaz-platform';
type Claims={sub:string;email:string;role:string;iss:string;aud:'anpardaz-ecosystem';iat:number;exp:number;phone?:string}; type AuthBody={email?:string;password?:string};
const b64=(v:string|Buffer)=>Buffer.from(v).toString('base64url');
async function hashPassword(p:string){const s=randomBytes(16).toString('base64url');const d=(await scrypt(p,s,64)) as Buffer;return `scrypt$${s}$${d.toString('base64url')}`;}
function normalizePhone(v:string){const d=v.replace(/[\s\-().]/g,'');if(d.startsWith('+98'))return '0'+d.slice(3);if(d.startsWith('0098'))return '0'+d.slice(4);if(d.startsWith('98')&&d.length===12)return '0'+d.slice(2);return d;}
const validPhone=(v:unknown)=>typeof v==='string'&&/^09\d{9}$/.test(normalizePhone(v));
function otpHash(phone:string,code:string){const secret=process.env.OTP_HASH_SECRET;if(!secret)throw new Error('otp_hash_secret_not_configured');return createHash('sha256').update(secret+'|'+phone+'|'+code).digest('hex');}
async function sendPhoneOtp(phone:string,code:string){if(process.env.PHONE_OTP_ENABLED!=='true')throw new Error('phone_otp_disabled');const key=process.env.KAVENEGAR_API_KEY?.trim(),sender=process.env.KAVENEGAR_SENDER?.trim()||'';if(!key||!sender)throw new Error('phone_otp_provider_not_configured');const body=new URLSearchParams({receptor:phone,message:'کد تأیید آن‌پرداز: '+code,sender});const res=await fetch('https://api.kavenegar.com/v1/'+encodeURIComponent(key)+'/sms/send.json',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body,signal:AbortSignal.timeout(10000)});const data=await res.json().catch(()=>({})) as any;if(!res.ok||Number(data?.return?.status)!==200)throw new Error('phone_otp_send_failed');}
async function verifyPassword(p:string,x:string){const parts=x.split('$');if(parts.length!==3||parts[0]!=='scrypt'||!parts[1]||!parts[2])return false;let expected:Buffer;try{expected=Buffer.from(parts[2],'base64url');}catch{return false;}if(expected.length!==64)return false;const actual=(await scrypt(p,parts[1],expected.length)) as Buffer;return timingSafeEqual(expected,actual);}
function createToken(c:Claims){const h=b64(JSON.stringify({alg:'EdDSA',typ:'JWT'})),p=b64(JSON.stringify(c));const s=signData(null,Buffer.from(`${h}.${p}`),privateKey).toString('base64url');return `${h}.${p}.${s}`;}
const valid=(b:AuthBody):b is Required<AuthBody>=>typeof b.email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email)&&typeof b.password==='string'&&b.password.length>=10&&b.password.length<=128;
let lastRateLimitCleanup=0;
async function allowAuthAttempt(pool:Pool,req:FastifyRequest,scope:string,identity:string,limit:number){const minute=new Date(Math.floor(Date.now()/60000)*60000);if(minute.getTime()-lastRateLimitCleanup>=600000){lastRateLimitCleanup=minute.getTime();await pool.query("DELETE FROM auth_rate_limits WHERE window_start < NOW() - INTERVAL '24 hours'").catch(()=>{});}const clientKey=createHash('sha256').update(`${scope}|${req.ip}|${identity.toLowerCase()}`).digest('hex');const r=await pool.query<{request_count:number}>(`INSERT INTO auth_rate_limits(scope,client_key,window_start,request_count) VALUES($1,$2,$3,1) ON CONFLICT(scope,client_key,window_start) DO UPDATE SET request_count=auth_rate_limits.request_count+1 RETURNING request_count`,[scope,clientKey,minute]);return r.rows[0].request_count<=limit;}
export async function ensurePlatformUser(pool:Pool,auth:Claims){const existing=await pool.query<{id:string}>('SELECT id FROM platform_users WHERE identity_id=$1 LIMIT 1',[auth.sub]);if(existing.rows[0]){await pool.query('UPDATE platform_users SET email=$1 WHERE id=$2',[auth.email,existing.rows[0].id]);return existing.rows[0].id;}const r=await pool.query<{id:string}>('INSERT INTO platform_users(identity_id,email,display_name,role) VALUES($1,$2,$3,$4) ON CONFLICT(identity_id) DO UPDATE SET email=EXCLUDED.email RETURNING id',[auth.sub,auth.email,auth.email.split('@')[0],auth.role]);return r.rows[0].id;}
export function registerAuthRoutes(app:{post:Function},pool:Pool){
 app.post('/api/v1/auth/register',async(req:FastifyRequest,reply:FastifyReply)=>{const b=(req.body??{}) as AuthBody;if(!valid(b))return reply.code(400).send({error:'invalid_credentials'});const email=b.email.trim().toLowerCase();if(!(await allowAuthAttempt(pool,req,'register',email,5)))return reply.code(429).send({error:'too_many_requests'});try{const r=await pool.query<{identity_id:string;role:string}>(`INSERT INTO platform_users(identity_id,email,password_hash,display_name,role) VALUES($1,$2,$3,$4,$5) RETURNING identity_id,role`,[randomUUID(),email,await hashPassword(b.password),email.split('@')[0],'user']);const u=r.rows[0],now=Math.floor(Date.now()/1000);return reply.code(201).send({accessToken:createToken({sub:u.identity_id,email,role:u.role,iss:issuer(),aud:'anpardaz-ecosystem',iat:now,exp:now+TOKEN_TTL_SECONDS}),expiresIn:TOKEN_TTL_SECONDS});}catch(e:any){if(e?.code==='23505')return reply.code(409).send({error:'email_already_registered'});req.log.error(e);return reply.code(500).send({error:'registration_failed'});}});
 app.post('/api/v1/auth/login',async(req:FastifyRequest,reply:FastifyReply)=>{const b=(req.body??{}) as AuthBody;if(!valid(b))return reply.code(400).send({error:'invalid_credentials'});const email=b.email.trim().toLowerCase();if(!(await allowAuthAttempt(pool,req,'login',email,10)))return reply.code(429).send({error:'too_many_requests'});const r=await pool.query<{identity_id:string;email:string;password_hash:string;role:string;status:string}>(`SELECT identity_id,email,password_hash,role,status FROM platform_users WHERE LOWER(email)=LOWER($1) LIMIT 1`,[email]);const u=r.rows[0];if(!u?.password_hash||u.status!=='active'||!(await verifyPassword(b.password,u.password_hash)))return reply.code(401).send({error:'invalid_credentials'});await pool.query('UPDATE platform_users SET last_login_at=NOW() WHERE identity_id=$1',[u.identity_id]).catch(()=>{});const now=Math.floor(Date.now()/1000);return {accessToken:createToken({sub:u.identity_id,email:u.email,role:u.role,iss:issuer(),aud:'anpardaz-ecosystem',iat:now,exp:now+TOKEN_TTL_SECONDS}),expiresIn:TOKEN_TTL_SECONDS};});
 app.post('/api/v1/auth/phone/request-otp',async(req:FastifyRequest,reply:FastifyReply)=>{
   const raw=String((req.body as any)?.phone??'').trim(),phone=normalizePhone(raw);
   if(!validPhone(phone))return reply.code(400).send({error:'invalid_phone'});
   if(!(await allowAuthAttempt(pool,req,'phone_otp_request',phone,3)))return reply.code(429).send({error:'too_many_requests'});
   if(process.env.PHONE_OTP_ENABLED!=='true')return reply.code(503).send({error:'phone_otp_disabled'});
   const code=String(randomInt(100000,1000000));
   try{await pool.query("UPDATE phone_otp_challenges SET consumed_at=NOW() WHERE phone=$1 AND consumed_at IS NULL",[phone]);await pool.query("INSERT INTO phone_otp_challenges(phone,code_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '2 minutes')",[phone,otpHash(phone,code)]);await sendPhoneOtp(phone,code);return{sent:true,expiresInSeconds:120};}
   catch(e){req.log.error(e);return reply.code(503).send({error:e instanceof Error?e.message:'phone_otp_send_failed'});}
 });
 app.post('/api/v1/auth/phone/verify-otp',async(req:FastifyRequest,reply:FastifyReply)=>{
   const raw=String((req.body as any)?.phone??'').trim(),phone=normalizePhone(raw),code=String((req.body as any)?.code??'').trim();
   if(!validPhone(phone)||!/^[0-9]{6}$/.test(code))return reply.code(400).send({error:'invalid_otp'});
   if(!(await allowAuthAttempt(pool,req,'phone_otp_verify',phone,10)))return reply.code(429).send({error:'too_many_requests'});
   const q=await pool.query<{id:string;code_hash:string;attempts:number}>('SELECT id,code_hash,attempts FROM phone_otp_challenges WHERE phone=$1 AND consumed_at IS NULL AND expires_at>NOW() ORDER BY id DESC LIMIT 1',[phone]);
   const challenge=q.rows[0];if(!challenge||Number(challenge.attempts)>=5)return reply.code(401).send({error:'invalid_otp'});
   if(challenge.code_hash!==otpHash(phone,code)){await pool.query("UPDATE phone_otp_challenges SET attempts=attempts+1 WHERE id=$1",[challenge.id]);return reply.code(401).send({error:'invalid_otp'});}
   const client=await pool.connect();
   try{await client.query('BEGIN');const email=phone+'@users.anpardaz.ir';const existing=await client.query<{identity_id:string;role:string;status:string}>("SELECT identity_id,role,status FROM platform_users WHERE phone=$1 OR LOWER(email)=LOWER($2) LIMIT 1 FOR UPDATE",[phone,email]);let identityId:string,role='user';if(existing.rows[0]){if(existing.rows[0].status!=='active')throw new Error('account_inactive');identityId=existing.rows[0].identity_id;role=existing.rows[0].role;await client.query('UPDATE platform_users SET phone=$1,last_login_at=NOW() WHERE identity_id=$2',[phone,identityId]);}else{identityId=randomUUID();await client.query("INSERT INTO platform_users(identity_id,phone,email,display_name,role,last_login_at) VALUES($1,$2,$3,$2,'user',NOW())",[identityId,phone,email]);}await client.query("UPDATE phone_otp_challenges SET consumed_at=NOW() WHERE id=$1",[challenge.id]);await client.query('COMMIT');const now=Math.floor(Date.now()/1000);return{accessToken:createToken({sub:identityId,email,role,iss:issuer(),aud:'anpardaz-ecosystem',iat:now,exp:now+TOKEN_TTL_SECONDS,phone}),expiresIn:TOKEN_TTL_SECONDS,phone};}
   catch(e){await client.query('ROLLBACK');if(e instanceof Error&&e.message==='account_inactive')return reply.code(403).send({error:'account_inactive'});req.log.error(e);return reply.code(500).send({error:'phone_auth_failed'});}
   finally{client.release();}
 });

}
export function verifyIdentityToken(t:string):Claims|null{if(typeof t!=='string'||t.length<32||t.length>8192)return null;const parts=t.split('.');if(parts.length!==3)return null;const[h,p,s]=parts;if(!h||!p||!s)return null;try{const header=JSON.parse(Buffer.from(h,'base64url').toString()) as {alg?:string;typ?:string};if(header.alg!=='EdDSA'||header.typ!=='JWT')return null;if(!verifyData(null,Buffer.from(`${h}.${p}`),publicKey,Buffer.from(s,'base64url')))return null;const c=JSON.parse(Buffer.from(p,'base64url').toString()) as Partial<Claims>;const now=Math.floor(Date.now()/1000);if(typeof c.sub!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(c.sub))return null;if(typeof c.email!=='string'||!valid({email:c.email,password:'0123456789'}))return null;if(c.phone!==undefined&&!validPhone(c.phone))return null;if(typeof c.role!=='string'||!['user','admin','super_admin','operator','editor','moderator','support'].includes(c.role))return null;if(c.aud!=='anpardaz-ecosystem'||c.iss!==issuer()||typeof c.iat!=='number'||typeof c.exp!=='number'||!Number.isSafeInteger(c.iat)||!Number.isSafeInteger(c.exp)||c.iat>now+60||c.exp<=now||c.exp>c.iat+TOKEN_TTL_SECONDS)return null;return c as Claims;}catch{return null;}}
export async function requireAuth(req:FastifyRequest,reply:FastifyReply){const h=req.headers.authorization;const c=h?.startsWith('Bearer ')?verifyIdentityToken(h.slice(7)):null;if(!c)return reply.code(401).send({error:'unauthorized'});const pool=(req.server as typeof req.server&{platformPool?:Pool}).platformPool;if(pool){const u=await pool.query<{status:string}>('SELECT status FROM platform_users WHERE identity_id=$1 LIMIT 1',[c.sub]);if(!u.rows[0]||u.rows[0].status!=='active')return reply.code(401).send({error:'unauthorized'});}else{return reply.code(503).send({error:'identity_service_unavailable'});}(req as FastifyRequest&{auth:Claims}).auth=c;}
export type AuthClaims=Claims;
