networks:
  anpardaz-internal:
    external: true

services:
    networks: [anpardaz-internal]
  admin:
    build:
      context: ../..
      dockerfile: services/admin/Dockerfile
    env_file:
      - admin.env
    restart: unless-stopped
    ports:
      - "127.0.0.1:4006:4006"
    read_only: true
    tmpfs:
      - /tmp

    networks: [anpardaz-internal]