import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify';
import type {Pool} from 'pg';
import {createHash} from 'node:crypto';
import {ensureCustomer,requireAuth,type AuthClaims} from '../auth.js';
import {decryptSecret,encryptSecret,FinnotechClient} from '../finnotech.js';
type R=FastifyRequest&{auth:AuthClaims}; const ar=(r:FastifyRequest)=>r as R;
const client=(reply:FastifyReply)=>{try{return new FinnotechClient()}catch{return void reply.code(503).send({error:'finnotech_not_configured'})}};
const path=()=>{const v=process.env.FINNOTECH_STATEMENT_PATH?.trim();if(!v)throw new Error('FINNOTECH_STATEMENT_PATH_not_configured');return v};
async function conn(pool:Pool,c:string){return(await pool.query(`SELECT * FROM finnotech_connections WHERE customer_id=$1 AND status='active' ORDER BY id DESC LIMIT 1`,[c])).rows[0]}
async function token(pool:Pool,row:any,c:FinnotechClient){if(row.access_token_expires_at&&new Date(row.access_token_expires_at).getTime()<Date.now()+30000&&row.refresh_token_enc){const x=await c.refresh(decryptSecret(row.refresh_token_enc));const a=String((x.access_token as any)?.value??x.access_token??'');const r=String((x.access_token as any)?.refreshToken??x.refresh_token??'');const e=Number((x.access_token as any)?.expiresIn??x.expires_in??3600);if(!a)throw new Error('finnotech_refresh_missing_access_token');await pool.query(`UPDATE finnotech_connections SET access_token_enc=$1,refresh_token_enc=$2,access_token_expires_at=NOW()+($3::text||' seconds')::interval,updated_at=NOW() WHERE id=$4`,[encryptSecret(a),r?encryptSecret(r):row.refresh_token_enc,e,row.id]);return a}return decryptSecret(row.access_token_enc)}
function arr(raw:any){for(const k of ['transactions','statement','items','data','results']){if(Array.isArray(raw?.[k]))return raw[k];if(Array.isArray(raw?.result?.[k]))return raw.result[k]}return Array.isArray(raw)?raw:[]}
function num(x:any){for(const v of [x.amount,x.amountValue,x.value,x.transactionAmount,x.creditAmount,x.debitAmount]){const n=Number(String(v??'').replace(/,/g,''));if(Number.isFinite(n)&&n>0)return Math.abs(n)}return null}
function date(x:any){for(const v of [x.occurredAt,x.transactionDate,x.date,x.createdAt,x.created_at,x.timestamp]){if(v){const d=new Date(v);if(!Number.isNaN(d.getTime()))return d}}return null}
function dir(x:any){const s=String(x.direction??x.type??x.transactionType??x.creditDebit??'').toLowerCase();if(/debit|expense|withdraw|برداشت|بدهکار/.test(s))return' expense'.trim();if(/credit|income|deposit|واریز|بستانکار/.test(s))return'income';const n=Number(String(x.amount??'').replace(/,/g,''));return n<0?'expense':'income'}
function cat(d:string,t:string){const n=d.toLowerCase();if(/قبض|برق|آب|گاز|مخابرات/.test(n))return'قبوض';if(/شارژ|اینترنت/.test(n))return'شارژ و اینترنت';if(/بیمه/.test(n))return'بیمه';if(/خلافی|عوارض|ترافیک/.test(n))return'حمل و نقل';if(/حقوق|دستمزد/.test(n))return'درآمد';if(/انتقال|کارت به کارت|پایا|ساتنا/.test(n))return t==='income'?'دریافت انتقال':'انتقال وجه';return t==='income'?'سایر درآمدها':'سایر هزینه‌ها'}
async function accountingPost(pool:Pool,customerId:string,cardId:number,externalId:string,amount:string,currency:string,direction:string,category:string,description:string){
 const base=process.env.ACCOUNTING_SERVICE_URL?.replace(/\/$/,'');const token=process.env.ACCOUNTING_INTERNAL_TOKEN;
 if(!base||!token)return {status:'not_configured'};
 const customer=(await pool.query('SELECT identity_id FROM customers WHERE id=$1',[customerId])).rows[0];if(!customer?.identity_id)return {status:'customer_identity_missing'};
 const assetCode=`ANP:BANKCARD:${cardId}`,counterCode=`ANP:${direction==='income'?'INCOME':'EXPENSE'}:${category||'OTHER'}`;
 async function account(code:string,name:string,type:string){const h={authorization:'Bearer '+token,'content-type':'application/json',accept:'application/json'};const g=await fetch(base+'/internal/v1/ledger/accounts/by-code/'+encodeURIComponent(code),{headers:h});if(g.ok)return(await g.json()).account;const p=await fetch(base+'/internal/v1/ledger/accounts',{method:'POST',headers:h,body:JSON.stringify({accountCode:code,accountName:name,accountType:type,ownerIdentityId:customer.identity_id,currency})});if(p.ok)return(await p.json()).account;const e=await p.json().catch(()=>({}));if(p.status===409){const again=await fetch(base+'/internal/v1/ledger/accounts/by-code/'+encodeURIComponent(code),{headers:h});if(again.ok)return(await again.json()).account}throw new Error(String(e.error??'account_create_failed'))}
 const asset=await account(assetCode,'حساب کارت بانکی '+cardId,'asset');const counter=await account(counterCode,counterCode,'income'===direction?'revenue':'expense');
 const entries=direction==='income'?[{accountId:Number(asset.id),direction:'debit',amount,currency,metadata:{source:'financial-center',category}},{accountId:Number(counter.id),direction:'credit',amount,currency,metadata:{source:'financial-center',category}}]:[{accountId:Number(counter.id),direction:'debit',amount,currency,metadata:{source:'financial-center',category}},{accountId:Number(asset.id),direction:'credit',amount,currency,metadata:{source:'financial-center',category}}];
 const r=await fetch(base+'/internal/v1/ledger/transactions',{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json',accept:'application/json'},body:JSON.stringify({referenceType:'ANPARDAZ_BANK_TRANSACTION',referenceId:externalId,idempotencyKey:'financial:'+cardId+':'+externalId,description:description||category,entries})});
 const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(body.error??'accounting_post_failed'));return{status:'posted',transaction:body.transaction};
}
async function createFinancialNotification(pool:Pool,customerId:string,cardId:number,type:string,title:string,body:string,metadata:any={}){
  await pool.query(`INSERT INTO financial_notifications(customer_id,card_id,type,title,body,metadata) VALUES($1,$2,$3,$4,$5,$6)`,[customerId,cardId,type,title,body,JSON.stringify(metadata)]);
}
async function sync(pool:Pool,c:string,card:any,fc:FinnotechClient,a:string){const ep=path().replace('{clientId}',encodeURIComponent(String(process.env.FINNOTECH_CLIENT_ID??''))).replace('{deposit}',encodeURIComponent(String(card.provider_account_id??'')));const raw=await fc.call(ep,a,undefined,'GET');const items=arr(raw);let imported=0;for(const x of items){const amount=num(x),when=date(x);if(!amount||!when)continue;const direction=dir(x),description=String(x.description??x.title??x.memo??x.note??'').slice(0,1000),external=String(x.id??x.transactionId??x.reference??x.traceId??'').trim()||createHash('sha256').update(JSON.stringify(x)).digest('hex');await pool.query(`INSERT INTO financial_card_transactions(customer_id,card_id,external_id,direction,amount,currency,description,category,occurred_at,source,raw_metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'FINNOTECH',$10) ON CONFLICT(card_id,external_id) DO UPDATE SET direction=EXCLUDED.direction,amount=EXCLUDED.amount,currency=EXCLUDED.currency,description=EXCLUDED.description,category=EXCLUDED.category,occurred_at=EXCLUDED.occurred_at,raw_metadata=EXCLUDED.raw_metadata`,[c,card.id,external,String(direction),amount,String(x.currency??card.currency??'IRR').toUpperCase().slice(0,3),description,cat(description,direction),when,JSON.stringify(x)]);let accounting='not_configured';try{accounting=(await accountingPost(pool,c,Number(card.id),external,String(amount),String(x.currency??card.currency??'IRR').toUpperCase().slice(0,3),String(direction),cat(description,direction),description)).status}catch(e){accounting=e instanceof Error?e.message:'accounting_failed'}imported++; }
  if(imported>0) await createFinancialNotification(pool,c,Number(card.id),'sync','مرکز مالی به‌روزرسانی شد',`گردش حساب کارت •••• ${card.last4} با ${imported} تراکنش جدید/به‌روزشده دریافت شد.`,{source:'FINNOTECH',imported});
  return{received:items.length,imported,accounting:'synchronous'} }
export function registerFinancialCenterRoutes(app:FastifyInstance,pool:Pool){
app.get('/api/v1/financial-center/cards',{preHandler:requireAuth},async(req)=>{const c=await ensureCustomer(pool,ar(req).auth);return{cards:(await pool.query(`SELECT c.id,c.last4,c.bank_name,c.status,c.account_id,a.currency,COALESCE(p.enabled,FALSE) audit_enabled,p.enabled_at,p.disabled_at FROM cards c JOIN accounts a ON a.id=c.account_id LEFT JOIN financial_card_audit_permissions p ON p.card_id=c.id AND p.customer_id=c.customer_id WHERE c.customer_id=$1 ORDER BY c.created_at DESC`,[c])).rows}});
app.get('/api/v1/financial-center/notifications',{preHandler:requireAuth},async(req)=>{
  const c=await ensureCustomer(pool,ar(req).auth);
  const rows=(await pool.query(`SELECT id,type,title,body,metadata,read_at,created_at FROM financial_notifications WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 100`,[c])).rows;
  return {notifications:rows,unreadCount:rows.filter((x:any)=>!x.read_at).length};
});
app.patch('/api/v1/financial-center/notifications/:id/read',{preHandler:requireAuth},async(req,reply)=>{
  const c=await ensureCustomer(pool,ar(req).auth),id=Number((req.params as any).id);
  if(!Number.isSafeInteger(id))return reply.code(400).send({error:'invalid_notification_id'});
  const x=await pool.query(`UPDATE financial_notifications SET read_at=COALESCE(read_at,NOW()) WHERE id=$1 AND customer_id=$2 RETURNING id,read_at`,[id,c]);
  if(!x.rows[0])return reply.code(404).send({error:'notification_not_found'});
  return {notification:x.rows[0]};
});
app.patch('/api/v1/financial-center/notifications/read-all',{preHandler:requireAuth},async(req)=>{
  const c=await ensureCustomer(pool,ar(req).auth);
  await pool.query(`UPDATE financial_notifications SET read_at=NOW() WHERE customer_id=$1 AND read_at IS NULL`,[c]);
  return {ok:true};
});
app.patch('/api/v1/financial-center/cards/:cardId/access',{preHandler:requireAuth},async(req,reply)=>{const c=await ensureCustomer(pool,ar(req).auth),id=Number((req.params as any).cardId),b=req.body as any;if(!Number.isSafeInteger(id)||typeof b?.enabled!=='boolean')return reply.code(400).send({error:'invalid_access_request'});const card=(await pool.query('SELECT id,status FROM cards WHERE id=$1 AND customer_id=$2',[id,c])).rows[0];if(!card)return reply.code(404).send({error:'card_not_found'});if(card.status!=='active')return reply.code(409).send({error:'card_not_active'});const x=await pool.query(`INSERT INTO financial_card_audit_permissions(customer_id,card_id,enabled,enabled_at,disabled_at) VALUES($1,$2,$3,CASE WHEN $3 THEN NOW() ELSE NULL END,CASE WHEN $3 THEN NULL ELSE NOW() END) ON CONFLICT(customer_id,card_id) DO UPDATE SET enabled=EXCLUDED.enabled,enabled_at=CASE WHEN EXCLUDED.enabled THEN NOW() ELSE financial_card_audit_permissions.enabled_at END,disabled_at=CASE WHEN EXCLUDED.enabled THEN NULL ELSE NOW() END,updated_at=NOW() RETURNING *`,[c,id,b.enabled]);return{permission:x.rows[0]}});
app.get('/api/v1/financial-center',{preHandler:requireAuth},async(req)=>{const c=await ensureCustomer(pool,ar(req).auth),q=req.query as any,to=new Date(q.end??Date.now()),from=new Date(q.start??(to.getTime()-30*86400000)),ids=String(q.cardIds??'').split(',').map(Number).filter(Number.isSafeInteger);const p:any[]=[c,from,to];const f=ids.length?(p.push(ids),' AND t.card_id=ANY($4::bigint[])'):'';const tx=await pool.query(`SELECT t.id,t.card_id,c.last4,t.direction,t.amount::text,t.currency,t.description,t.category,t.occurred_at FROM financial_card_transactions t JOIN cards c ON c.id=t.card_id JOIN financial_card_audit_permissions p ON p.card_id=t.card_id AND p.customer_id=t.customer_id AND p.enabled=TRUE WHERE t.customer_id=$1 AND t.occurred_at>=$2 AND t.occurred_at<$3${f} ORDER BY t.occurred_at DESC LIMIT 1000`,p);const s=await pool.query(`SELECT direction,COALESCE(SUM(amount),0)::text total FROM financial_card_transactions t JOIN financial_card_audit_permissions p ON p.card_id=t.card_id AND p.customer_id=t.customer_id AND p.enabled=TRUE WHERE t.customer_id=$1 AND t.occurred_at>=$2 AND t.occurred_at<$3${f} GROUP BY direction`,p);const bc=await pool.query(`SELECT COALESCE(category,'سایر') category,direction,COALESCE(SUM(amount),0)::text total FROM financial_card_transactions t JOIN financial_card_audit_permissions p ON p.card_id=t.card_id AND p.customer_id=t.customer_id AND p.enabled=TRUE WHERE t.customer_id=$1 AND t.occurred_at>=$2 AND t.occurred_at<$3${f} GROUP BY category,direction ORDER BY SUM(amount) DESC`,p);return{range:{start:from.toISOString(),end:to.toISOString()},transactions:tx.rows,summary:s.rows,byCategory:bc.rows}});
app.post('/api/v1/financial-center/sync',{preHandler:requireAuth},async(req,reply)=>{const c=await ensureCustomer(pool,ar(req).auth),cn=await conn(pool,c);if(!cn)return reply.code(409).send({error:'finnotech_not_connected'});const fc=client(reply);if(!fc)return;const a=await token(pool,cn,fc);const cards=(await pool.query(`SELECT c.*,a.currency,a.provider_account_id FROM cards c JOIN accounts a ON a.id=c.account_id JOIN financial_card_audit_permissions p ON p.card_id=c.id AND p.customer_id=c.customer_id AND p.enabled=TRUE WHERE c.customer_id=$1 AND c.status='active'`,[c])).rows;const results=[];for(const card of cards){try{results.push({cardId:card.id,...await sync(pool,c,card,fc,a),status:'completed'})}catch(e){results.push({cardId:card.id,status:'failed',error:e instanceof Error?e.message:'sync_failed'})}}return{results}});
app.post('/internal/v1/financial-center/sync-all',async(req,reply)=>{
  const internal=process.env.ANPARDAZ_INTERNAL_TOKEN;
  if(!internal||req.headers.authorization!==`Bearer ${internal}`)return reply.code(401).send({error:'unauthorized'});
  const rows=(await pool.query(`SELECT DISTINCT c.id AS card_id,c.customer_id FROM cards c JOIN financial_card_audit_permissions p ON p.card_id=c.id AND p.customer_id=c.customer_id AND p.enabled=TRUE JOIN finnotech_connections fc ON fc.customer_id=c.customer_id AND fc.status='active' WHERE c.status='active' ORDER BY c.customer_id,c.id`)).rows;
  const grouped=new Map<string,number[]>();
  for(const row of rows){const key=String(row.customer_id);const list=grouped.get(key)??[];list.push(Number(row.card_id));grouped.set(key,list);}
  const results:any[]=[];
  const fc=client(reply);if(!fc)return;
  for(const [customerId,cardIds] of grouped){
    try{
      const cn=await conn(pool,customerId);if(!cn)continue;
      const access=await token(pool,cn,fc);
      const cards=(await pool.query(`SELECT c.*,a.currency,a.provider_account_id FROM cards c JOIN accounts a ON a.id=c.account_id JOIN financial_card_audit_permissions p ON p.card_id=c.id AND p.customer_id=c.customer_id AND p.enabled=TRUE WHERE c.customer_id=$1 AND c.id=ANY($2::bigint[]) AND c.status='active'`,[customerId,cardIds])).rows;
      for(const card of cards){try{results.push({customerId,cardId:card.id,...await sync(pool,customerId,card,fc,access),status:'completed'})}catch(e){results.push({customerId,cardId:card.id,status:'failed',error:e instanceof Error?e.message:'sync_failed'})}}
    }catch(e){results.push({customerId,status:'failed',error:e instanceof Error?e.message:'customer_sync_failed'})}
  }
  return {results};
});
app.get('/internal/v1/admin/financial-center/:identityId',async(req,reply)=>{const tokenv=process.env.ANPARDAZ_INTERNAL_TOKEN;if(!tokenv||req.headers.authorization!==`Bearer ${tokenv}`)return reply.code(401).send({error:'unauthorized'});const id=String((req.params as any).identityId??'').trim(),customer=(await pool.query('SELECT id,identity_id,external_user_id,email,status FROM customers WHERE identity_id=$1',[id])).rows[0];if(!customer)return reply.code(404).send({error:'customer_not_found'});const [cards,tx]=await Promise.all([pool.query(`SELECT c.id,c.last4,c.status,a.currency,COALESCE(p.enabled,FALSE) audit_enabled FROM cards c JOIN accounts a ON a.id=c.account_id LEFT JOIN financial_card_audit_permissions p ON p.card_id=c.id AND p.customer_id=c.customer_id WHERE c.customer_id=$1 ORDER BY c.id`,[customer.id]),pool.query(`SELECT t.id,t.card_id,c.last4,t.direction,t.amount::text,t.currency,t.description,t.category,t.occurred_at FROM financial_card_transactions t JOIN cards c ON c.id=t.card_id WHERE t.customer_id=$1 ORDER BY t.occurred_at DESC LIMIT 5000`,[customer.id])]);const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=['id,card_last4,direction,amount,currency,category,occurred_at,description',...tx.rows.map(x=>[x.id,x.last4,x.direction,x.amount,x.currency,x.category,x.occurred_at,x.description].map(esc).join(','))].join('\\n');return{customer,cards:cards.rows,transactions:tx.rows,csv}});}