import type { Pool } from 'pg';

type Quote={symbol:string;bid?:string;ask?:string;lastPrice?:string;volume24h?:string;sourceTimestamp?:string};
export interface MarketDataAdapter{readonly name:string;fetchQuote(symbol:string):Promise<Quote|null>}
async function getJson(url:string,timeoutMs=5000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(url,{signal:controller.signal,headers:{accept:'application/json'}});if(!r.ok)throw new Error(`HTTP_${r.status}`);return await r.json() as any;}finally{clearTimeout(timer);}}
const decimal=(v:unknown)=>typeof v==='string'&&/^(?:0|[1-9]\d{0,37})(?:\.\d{1,18})?$/.test(v)?v:null;
const sourceSymbol=(symbol:string)=>symbol.replace(/[-_/]/g,'').toUpperCase();
const nobitexPair=(symbol:string)=>{const [base,quote]=symbol.toUpperCase().split('-');const q=quote==='IRT'||quote==='IRR'?'rls':quote?.toLowerCase();return base&&q?`${base.toLowerCase()}-${q}`:null;};
function midpoint(a?:string,b?:string){if(!a||!b)return a??b;const [ai,af='']=a.split('.'),[bi,bf='']=b.split('.');const scale=Math.max(af.length,bf.length);const A=BigInt(ai)*10n**BigInt(scale)+BigInt(af.padEnd(scale,'0')||'0');const B=BigInt(bi)*10n**BigInt(scale)+BigInt(bf.padEnd(scale,'0')||'0');const M=(A+B)/2n;const s=M.toString().padStart(scale+1,'0');return scale?`${s.slice(0,-scale)}.${s.slice(-scale)}`:s;}

export class WallexAdapter implements MarketDataAdapter{readonly name='wallex';async fetchQuote(symbol:string){const data=await getJson('https://api.wallex.ir/v1/markets');const item=data?.result?.symbols?.[sourceSymbol(symbol)];if(!item)return null;return{symbol,bid:decimal(item.stats?.bidPrice)??undefined,ask:decimal(item.stats?.askPrice)??undefined,lastPrice:decimal(item.stats?.lastPrice)??undefined,volume24h:decimal(item.stats?.['24h_volume'])??undefined};}}
export class NobitexAdapter implements MarketDataAdapter{readonly name='nobitex';async fetchQuote(symbol:string){const pair=nobitexPair(symbol);if(!pair)return null;const [base,quote]=pair.split('-');const data=await getJson(`https://api.nobitex.ir/market/stats?srcCurrency=${encodeURIComponent(base)}&dstCurrency=${encodeURIComponent(quote)}`);const item=data?.stats?.[pair];if(!item)return null;return{symbol,bid:decimal(item.bestBuy)??undefined,ask:decimal(item.bestSell)??undefined,lastPrice:decimal(item.latest)??undefined,volume24h:decimal(item.volumeSrc)??undefined};}}
export class TabdealAdapter implements MarketDataAdapter{readonly name='tabdeal';async fetchQuote(symbol:string){const data=await getJson(`https://api1.tabdeal.org/r/api/v1/depth?symbol=${encodeURIComponent(sourceSymbol(symbol))}&limit=1`);const bid=decimal(data?.bids?.[0]?.[0])??undefined,ask=decimal(data?.asks?.[0]?.[0])??undefined;return{symbol,bid,ask,lastPrice:midpoint(bid,ask)};}}

export class MarketDataService{constructor(private readonly pool:Pool,private readonly adapters:MarketDataAdapter[]){ }
 async ingest(symbols:string[]){for(const symbol of symbols){for(const adapter of this.adapters){const source=await this.pool.query<{id:string}>('SELECT id FROM market_data_sources WHERE name=$1 AND enabled=true',[adapter.name]);if(!source.rows[0])continue;try{const q=await adapter.fetchQuote(symbol);if(!q)continue;const s=await this.pool.query<{id:string}>('SELECT id FROM market_data_symbols WHERE symbol=$1 AND enabled=true',[symbol]);if(!s.rows[0])continue;await this.pool.query('INSERT INTO market_data_observations(source_id,symbol_id,bid,ask,last_price,volume_24h,source_timestamp) VALUES($1,$2,$3,$4,$5,$6,$7)',[source.rows[0].id,s.rows[0].id,q.bid??null,q.ask??null,q.lastPrice??null,q.volume24h??null,q.sourceTimestamp?new Date(q.sourceTimestamp):new Date()]);await this.pool.query("INSERT INTO market_data_health(source_id,status,last_success_at,consecutive_failures,last_error,updated_at) VALUES($1,'healthy',NOW(),0,NULL,NOW()) ON CONFLICT(source_id) DO UPDATE SET status='healthy',last_success_at=NOW(),consecutive_failures=0,last_error=NULL,updated_at=NOW()",[source.rows[0].id]);}catch(error){await this.pool.query("INSERT INTO market_data_health(source_id,status,last_failure_at,consecutive_failures,last_error,updated_at) VALUES($1,'degraded',NOW(),1,$2,NOW()) ON CONFLICT(source_id) DO UPDATE SET status=CASE WHEN market_data_health.consecutive_failures+1>=5 THEN 'down' ELSE 'degraded' END,last_failure_at=NOW(),consecutive_failures=market_data_health.consecutive_failures+1,last_error=$2,updated_at=NOW()",[source.rows[0].id,error instanceof Error?error.message:'market_data_error']);}}}}
}
