BEGIN;
-- Real-store registry expansion. Entries are inactive until An Market verifies domain, terms and a permitted feed/API.
INSERT INTO market_stores(name,slug,domain,homepage_url,category_hint,active,iframe_mode,feed_type) VALUES
('ترب','torob','torob.com','https://torob.com','general',FALSE,'unknown','manual'),
('ایمالز','emalls','emalls.ir','https://emalls.ir','general',FALSE,'unknown','manual'),
('لیپک','lipak','lipak.com','https://lipak.com','mobile-digital',FALSE,'unknown','manual'),
('یدک‌یار','yadakyar','yadakyar.com','https://yadakyar.com','automotive',FALSE,'unknown','manual'),
('تگموند','tagmond','tagmond.com','https://tagmond.com','fashion',FALSE,'unknown','manual'),
('روبان','roban','roban.ir','https://roban.ir','beauty-health',FALSE,'unknown','manual'),
('آداک','adak','adak.ir','https://adak.ir','digital',FALSE,'unknown','manual'),
('گیزدین','gizdin','gizdin.ir','https://gizdin.ir','digital',FALSE,'unknown','manual'),
('های‌شیائومی','hixiaomi','hixiaomi.ir','https://hixiaomi.ir','mobile-digital',FALSE,'unknown','manual'),
('لباسچی','lebaschi','lebaschi.com','https://lebaschi.com','fashion',FALSE,'unknown','manual'),
('برقچی','barghchi','barghchi.com','https://barghchi.com','tools-industrial',FALSE,'unknown','manual'),
('نورنگار','noornegar','noornegar.com','https://noornegar.com','audio-video',FALSE,'unknown','manual'),
('گیشا اسپرت','gishasport','gishasport.com','https://gishasport.com','sports',FALSE,'unknown','manual'),
('عطارک','attarak','attarak.com','https://attarak.com','beauty-health',FALSE,'unknown','manual'),
('دما تجهیز','damatajhiz','damatajhiz.com','https://damatajhiz.com','tools-industrial',FALSE,'unknown','manual'),
('شرف آنلاین','sharafonline','sharafonline.ir','https://sharafonline.ir','jewelry-gold',FALSE,'unknown','manual'),
('دیجی زرگر','digizargar','digizargar.com','https://digizargar.com','jewelry-gold',FALSE,'unknown','manual'),
('روبی گلد','rubygold','rubygold.ir','https://rubygold.ir','jewelry-gold',FALSE,'unknown','manual'),
('داروبوم','darooboom','darooboom.com','https://darooboom.com','beauty-health',FALSE,'unknown','manual'),
('بتادارو','betadarou','betadarou.com','https://betadarou.com','beauty-health',FALSE,'unknown','manual'),
('الانزا','elanza','elanza.com','https://elanza.com','beauty-health',FALSE,'unknown','manual'),
('کادولین','kadolin','kadolin.ir','https://kadolin.ir','beauty-health',FALSE,'unknown','manual'),
('بارجیل','barjil','barjil.com','https://barjil.com','supermarket',FALSE,'unknown','manual'),
('کاله','kalleh','kalleh.com','https://kalleh.com','supermarket',FALSE,'unknown','manual'),
('انتخاب سنتر','entekhabcenter','entekhabcenter.com','https://entekhabcenter.com','home-appliance',FALSE,'unknown','manual'),
('اگزو گیم','exogame','exogame.ir','https://exogame.ir','audio-video',FALSE,'unknown','manual'),
('مارال چرم','mymaral','mymaral.com','https://mymaral.com','fashion',FALSE,'unknown','manual'),
('آیفونچی','iphonechi','iphonechi.com','https://iphonechi.com','mobile-digital',FALSE,'unknown','manual'),
('پایتخت کتاب','paytakhtketab','paytakhteketab.com','https://paytakhteketab.com','books-culture',FALSE,'unknown','manual'),
('کتابچی','ketabchi','ketabchi.com','https://ketabchi.com','books-culture',FALSE,'unknown','manual'),
('گلد نهال','goldnahal','goldnahal.ir','https://goldnahal.ir','travel-camping',FALSE,'unknown','manual'),
('بست چاینا','bestchina','bestchina.ir','https://bestchina.ir','mobile-digital',FALSE,'unknown','manual'),
('دکورشاپ','decorshop','decorshop.ir','https://decorshop.ir','home-appliance',FALSE,'unknown','manual'),
('کافه مافی','cafimafi','cafimafi.com','https://cafimafi.com','supermarket',FALSE,'unknown','manual'),
('گیلان کشت','gilankesht','gilankesht.ir','https://gilankesht.ir','supermarket',FALSE,'unknown','manual'),
('پاییز کمپ','paeezcamp','paeezcamp.ir','https://paeezcamp.ir','travel-camping',FALSE,'unknown','manual'),
('پلی تهران','polytehran','polytehran.ir','https://polytehran.ir','tools-industrial',FALSE,'unknown','manual'),
('گلستان استیل','golestansteel','golestansteel.ir','https://golestansteel.ir','home-appliance',FALSE,'unknown','manual'),
('یواستور','yoostore','yoostore.ir','https://yoostore.ir','books-culture',FALSE,'unknown','manual'),
('اورجینال تهران','orginaltehran','orginaltehran.com','https://orginaltehran.com','home-appliance',FALSE,'unknown','manual'),
('لافارر','lafarrerr','lafarrerr.com','https://lafarrerr.com','beauty-health',FALSE,'unknown','manual'),
('داروکده','darukade','darukade.com','https://darukade.com','beauty-health',FALSE,'unknown','manual'),
('ایرانسل','irancell','irancell.ir','https://irancell.ir','mobile-digital',FALSE,'unknown','manual'),
('رمان بوک','romanbook','romanbook.ir','https://romanbook.ir','books-culture',FALSE,'unknown','manual'),
('نوین','novin','novin.com','https://novin.com','office',FALSE,'unknown','manual'),
('تخفیفان','takhfifan','takhfifan.com','https://takhfifan.com','other',FALSE,'unknown','manual'),
('پگاه','pegah','pegah.ir','https://pegah.ir','supermarket',FALSE,'unknown','manual'),
('میهن','mihan','mihan.ir','https://mihan.ir','supermarket',FALSE,'unknown','manual'),
('اسنپ مارکت','snappmarket','snappmarket.ir','https://snappmarket.ir','supermarket',FALSE,'unknown','manual'),
('اسنپ فود','snappfood','snappfood.ir','https://snappfood.ir','supermarket',FALSE,'unknown','manual'),
('کتابراه','ketabrah','ketabrah.ir','https://ketabrah.ir','books-culture',FALSE,'unknown','manual'),
('موبایل ۱۴۰','mobile140','mobile140.com','https://mobile140.com','mobile-digital',FALSE,'unknown','manual'),
('تکنوسان','technosun','technosun.ir','https://technosun.ir','laptop-computer',FALSE,'unknown','manual'),
('موبایل آباد','mobileabad','mobileabad.ir','https://mobileabad.ir','mobile-digital',FALSE,'unknown','manual'),
('پاپیون','papion','papion.com','https://papion.com','fashion',FALSE,'unknown','manual'),
('شیک پوش','shikpoosh','shikpoosh.com','https://shikpoosh.com','fashion',FALSE,'unknown','manual'),
('موبایل کمک','mobilekomak','mobilekomak.com','https://mobilekomak.com','mobile-digital',FALSE,'unknown','manual'),
('ایران جیب','iranjib','iranjib.ir','https://iranjib.ir','automotive',FALSE,'unknown','manual'),
('خودرو ۴۵','khodro45','khodro45.com','https://khodro45.com','automotive',FALSE,'unknown','manual'),
('دنیای خودرو','donyayekhodro','donyayekhodro.com','https://donyayekhodro.com','automotive',FALSE,'unknown','manual'),
('کارنوژن','karnogen','karnogen.com','https://karnogen.com','automotive',FALSE,'unknown','manual'),
('چرم مشهد','charmmashhad','charmmashhad.ir','https://charmmashhad.ir','fashion',FALSE,'unknown','manual'),
('چرم درسا','dorsa','dorsagroup.com','https://dorsagroup.com','fashion',FALSE,'unknown','manual'),
('کفش ملی','melli','mellishoes.ir','https://mellishoes.ir','fashion',FALSE,'unknown','manual'),
('کفش شیما','shima','shimashoes.ir','https://shimashoes.ir','fashion',FALSE,'unknown','manual'),
('دیجی‌رو','digiro','digiro.ir','https://digiro.ir','digital',FALSE,'unknown','manual'),
('آی تی هوم','ithome','ithome.ir','https://ithome.ir','digital',FALSE,'unknown','manual'),
('آی تی بازار','itbazaar','itbazaar.com','https://itbazaar.com','digital',FALSE,'unknown','manual'),
('فروشگاه مجید','majidshop','majidonline.com','https://majidonline.com','audio-video',FALSE,'unknown','manual'),
('فروشگاه دوربین','doorbin','doorbin.ir','https://doorbin.ir','audio-video',FALSE,'unknown','manual'),
('پرشین تولز','persiantools','persiantools.com','https://persiantools.com','tools-industrial',FALSE,'unknown','manual'),
('ابزارمارکت','abzarmarket','abzarmarket.com','https://abzarmarket.com','tools-industrial',FALSE,'unknown','manual'),
('ابزارلاین','abzarline','abzarline.com','https://abzarline.com','tools-industrial',FALSE,'unknown','manual'),
('ایران ابزار','iranabzar','iranabzar.com','https://iranabzar.com','tools-industrial',FALSE,'unknown','manual'),
('خانه ابزار','khanehabzar','khanehabzar.com','https://khanehabzar.com','tools-industrial',FALSE,'unknown','manual'),
('هوم‌کالا','homekala','homekala.ir','https://homekala.ir','home-appliance',FALSE,'unknown','manual'),
('لوازم خانگی بانه','banehkala','banehkala.com','https://banehkala.com','home-appliance',FALSE,'unknown','manual'),
('آی‌کالا','ikala','ikala.ir','https://ikala.ir','home-appliance',FALSE,'unknown','manual'),
('کالای خانه','kalayekhane','kalayekhaneh.com','https://kalayekhaneh.com','home-appliance',FALSE,'unknown','manual'),
('آجیل شور و شیرین','ajilstore','ajilstore.ir','https://ajilstore.ir','supermarket',FALSE,'unknown','manual'),
('خشکبار سنجاب','sanjab','sanjab.ir','https://sanjab.ir','supermarket',FALSE,'unknown','manual'),
('مسترکالا','masterkala','masterkala.com','https://masterkala.com','general',FALSE,'unknown','manual'),
('کالاچاپ','kalachap','kalachap.com','https://kalachap.com','office',FALSE,'unknown','manual'),
('کتاب فردا','ketabfarda','ketabfarda.com','https://ketabfarda.com','books-culture',FALSE,'unknown','manual'),
('کتاب گالری','ketabgallery','ketabgallery.com','https://ketabgallery.com','books-culture',FALSE,'unknown','manual'),
('آرایشی روبی','rubycosmetic','rubycosmetic.ir','https://rubycosmetic.ir','beauty-health',FALSE,'unknown','manual'),
('فروشگاه بچگانه','bacheganeh','bacheganeh.com','https://bacheganeh.com','baby-kids',FALSE,'unknown','manual'),
('نی نی کالا','ninikala','ninikala.com','https://ninikala.com','baby-kids',FALSE,'unknown','manual'),
('کودک آنلاین','koodakonline','koodakonline.com','https://koodakonline.com','baby-kids',FALSE,'unknown','manual'),
('پت شاپ ایران','petshopiran','petshopiran.com','https://petshopiran.com','pet',FALSE,'unknown','manual'),
('پت‌کالا','petkala','petkala.ir','https://petkala.ir','pet',FALSE,'unknown','manual'),
('پت‌لند','petland','petland.ir','https://petland.ir','pet',FALSE,'unknown','manual'),
('کمپینگ من','campingman','campingman.ir','https://campingman.ir','travel-camping',FALSE,'unknown','manual'),
('طبیعت گرد','tabiatgard','tabiatgard.com','https://tabiatgard.com','travel-camping',FALSE,'unknown','manual'),
('ورزش کالا','varzeshkala','varzeshkala.com','https://varzeshkala.com','sports',FALSE,'unknown','manual'),
('فروشگاه اسپرت','sportstore','sportstore.ir','https://sportstore.ir','sports',FALSE,'unknown','manual'),
('جواهری آنلاین','javaheri','javaheri.ir','https://javaheri.ir','jewelry-gold',FALSE,'unknown','manual'),
('گالری طلا','gallerygold','gallerygold.ir','https://gallerygold.ir','jewelry-gold',FALSE,'unknown','manual'),
('اداری شاپ','edarishop','edarishop.ir','https://edarishop.ir','office',FALSE,'unknown','manual'),
('لوازم التحریر آنلاین','stationeryonline','stationeryonline.ir','https://stationeryonline.ir','office',FALSE,'unknown','manual'),
('پلاس‌مارکت','plusmarket','plusmarket.ir','https://plusmarket.ir','general',FALSE,'unknown','manual'),
('بازرگام','bazargam','bazargam.com','https://bazargam.com','supermarket',FALSE,'unknown','manual'),
('پاییز کمپ','paeezcamp2','paeezcamp.ir','https://paeezcamp.ir','travel-camping',FALSE,'unknown','manual'),
('ایسام','esam2','esam.ir','https://esam.ir','general',FALSE,'unknown','manual'),
('مالتینا','malltina2','malltina.com','https://malltina.com','general',FALSE,'unknown','manual'),
('پیندو','pindo2','pindo.ir','https://pindo.ir','general',FALSE,'unknown','manual'),
('شهرکتاب آنلاین','shahreketab2','shahreketabonline.com','https://shahreketabonline.com','books-culture',FALSE,'unknown','manual')
ON CONFLICT(domain) DO NOTHING;
INSERT INTO schema_migrations(version) VALUES ('040_market_store_registry_wave3') ON CONFLICT(version) DO NOTHING;
COMMIT;