BEGIN;
-- 041: additional real-store candidates. Inactive until verified onboarding/feed approval.
INSERT INTO market_stores(name,slug,domain,homepage_url,category_hint,active,iframe_mode,feed_type) VALUES
('نورنگار','noornegar2','noornegar.com','https://noornegar.com','audio-video',FALSE,'unknown','manual'),
('گلد نهال','goldnahal2','goldnahal.ir','https://goldnahal.ir','other',FALSE,'unknown','manual'),
('سایاخودرو','sayakhodro','sayakhodro.com','https://sayakhodro.com','automotive',FALSE,'unknown','manual'),
('مانی نی','maninimarket','maninimarket.ir','https://maninimarket.ir','baby-kids',FALSE,'unknown','manual'),
('دینه ایران','dinehiran2','dineh.ir','https://dineh.ir','beauty-health',FALSE,'unknown','manual'),
('دلوکس گلامور','deluxeglamour','deluxeglamour.com','https://deluxeglamour.com','jewelry-gold',FALSE,'unknown','manual'),
('دوربین','camera-shop','camera-shop.ir','https://camera-shop.ir','audio-video',FALSE,'unknown','manual'),
('ایکس‌گیم','xgame','xgame.ir','https://xgame.ir','audio-video',FALSE,'unknown','manual'),
('آی‌تی مال','itmall','itmall.ir','https://itmall.ir','digital',FALSE,'unknown','manual'),
('پارس خزر','parskhazar','parskhazar.com','https://parskhazar.com','home-appliance',FALSE,'unknown','manual'),
('اسنوا','snowa','snowa.ir','https://snowa.ir','home-appliance',FALSE,'unknown','manual'),
('پاکشوما','pakshoma','pakshoma.com','https://pakshoma.com','home-appliance',FALSE,'unknown','manual'),
('دوو ایران','daewoo','daewoo.ir','https://daewoo.ir','home-appliance',FALSE,'unknown','manual'),
('جی‌پلاس','gplus','gplus.ir','https://gplus.ir','home-appliance',FALSE,'unknown','manual'),
('انتخاب الکترونیک','entekhab','entekhabgroup.com','https://entekhabgroup.com','home-appliance',FALSE,'unknown','manual'),
('دیجی‌کالا کالا','digikala-kala','digikala.com','https://digikala.com','general',FALSE,'unknown','manual'),
('فروشگاه افق کوروش','okcs','okcs.com','https://okcs.com','supermarket',FALSE,'unknown','manual'),
('جانبو','janbo','janbo.com','https://janbo.com','supermarket',FALSE,'unknown','manual'),
('هایپرمی','hyperme','hyperme.ir','https://hyperme.ir','supermarket',FALSE,'unknown','manual'),
('دیلی مارکت','dailymarket','dailymarket.ir','https://dailymarket.ir','supermarket',FALSE,'unknown','manual'),
('اسنپ اکسپرس','snapp-express','snappmarket.ir','https://snappmarket.ir','supermarket',FALSE,'unknown','manual'),
('فروشگاه هفت','haft','haft.ir','https://haft.ir','supermarket',FALSE,'unknown','manual'),
('فروشگاه شهرما','shahrma','shahrma.ir','https://shahrma.ir','supermarket',FALSE,'unknown','manual'),
('فروشگاه رفاه','refah','refah.ir','https://refah.ir','supermarket',FALSE,'unknown','manual'),
('اکالا پلاس','okala-plus','okala.com','https://okala.com','supermarket',FALSE,'unknown','manual'),
('گاج مارکت','gajmarket','gajmarket.com','https://gajmarket.com','books-culture',FALSE,'unknown','manual'),
('موسسه گاج','gaj','gaj.ir','https://gaj.ir','books-culture',FALSE,'unknown','manual'),
('مدرسان شریف','modaresan','modaresanesharif.ac.ir','https://modaresanesharif.ac.ir','books-culture',FALSE,'unknown','manual'),
('رشد','roshd','roshd.ir','https://roshd.ir','books-culture',FALSE,'unknown','manual'),
('کتابستان','ketabestan','ketabestan.com','https://ketabestan.com','books-culture',FALSE,'unknown','manual'),
('بوک‌لند','bookland','bookland.ir','https://bookland.ir','books-culture',FALSE,'unknown','manual'),
('کتاب جم','ketabjam','ketabjam.com','https://ketabjam.com','books-culture',FALSE,'unknown','manual'),
('فروشگاه مهر','mehrshop','mehrshop.ir','https://mehrshop.ir','general',FALSE,'unknown','manual'),
('روژان','rojanshop','rojanshop.ir','https://rojanshop.ir','beauty-health',FALSE,'unknown','manual'),
('مفید','mofidshop','mofidshop.ir','https://mofidshop.ir','beauty-health',FALSE,'unknown','manual'),
('داروخانه آنلاین ۲۴','darukhane24','darukhane24.com','https://darukhane24.com','beauty-health',FALSE,'unknown','manual'),
('مثبت سبز','mosbate-sabz','mosbatesabz.com','https://mosbatesabz.com','beauty-health',FALSE,'unknown','manual'),
('داروخانه مفید','darukhanemofid','darukhanemofid.ir','https://darukhanemofid.ir','beauty-health',FALSE,'unknown','manual'),
('مو تن رو','mootanroo3','mootanroo.com','https://mootanroo.com','beauty-health',FALSE,'unknown','manual'),
('خانومی','khanoumi3','khanoumi.com','https://khanoumi.com','beauty-health',FALSE,'unknown','manual'),
('شاپرزفا','shoppersfa','shoppersfa.com','https://shoppersfa.com','fashion',FALSE,'unknown','manual'),
('مد و پوشاک ایرانی','iranfashion','iranfashion.ir','https://iranfashion.ir','fashion',FALSE,'unknown','manual'),
('ژینورا','jinora','jinora.com','https://jinora.com','fashion',FALSE,'unknown','manual'),
('بادی اسپینر','bodyspinner2','bodyspinner.ir','https://bodyspinner.ir','sports',FALSE,'unknown','manual'),
('پادرا','padra','padra.ir','https://padra.ir','fashion',FALSE,'unknown','manual'),
('دیجی‌پوش','digipoosh','digipoosh.com','https://digipoosh.com','fashion',FALSE,'unknown','manual'),
('پوشاک سالیان','salian','salian.ir','https://salian.ir','fashion',FALSE,'unknown','manual'),
('هفت و هشت','haftohasht','haftohasht.com','https://haftohasht.com','fashion',FALSE,'unknown','manual'),
('چرم نگار','charmnegar','charmnegar.ir','https://charmnegar.ir','fashion',FALSE,'unknown','manual'),
('ایران تایر','irantire','irantire.com','https://irantire.com','automotive',FALSE,'unknown','manual'),
('لاستیک بارز','barez','barez.org','https://barez.org','automotive',FALSE,'unknown','manual'),
('لاستیک یزد','yazdtire','yazdtire.com','https://yazdtire.com','automotive',FALSE,'unknown','manual'),
('یدک‌سنتر','yadakcenter','yadakcenter.com','https://yadakcenter.com','automotive',FALSE,'unknown','manual'),
('اتوپارت','autopart','autopart.ir','https://autopart.ir','automotive',FALSE,'unknown','manual'),
('لوازم یدکی کار','yadakicar','yadakicar.com','https://yadakicar.com','automotive',FALSE,'unknown','manual'),
('موتور آنلاین','motoronline','motoronline.ir','https://motoronline.ir','automotive',FALSE,'unknown','manual'),
('دیجی‌کالا موتور','digikalamotor','digikala.com','https://digikala.com','automotive',FALSE,'unknown','manual'),
('کمپ‌مارکت','campmarket','campmarket.ir','https://campmarket.ir','travel-camping',FALSE,'unknown','manual'),
('کوه‌مارکت','koohmarket','koohmarket.ir','https://koohmarket.ir','travel-camping',FALSE,'unknown','manual'),
('آف‌کمپ','offcamp','offcamp.ir','https://offcamp.ir','travel-camping',FALSE,'unknown','manual'),
('فروشگاه طبیعت','naturestore','naturestore.ir','https://naturestore.ir','travel-camping',FALSE,'unknown','manual'),
('پت‌چی','petchi','petchi.ir','https://petchi.ir','pet',FALSE,'unknown','manual'),
('پت‌مارکت','petmarket','petmarket.ir','https://petmarket.ir','pet',FALSE,'unknown','manual'),
('پت‌هوم','pethome','pethome.ir','https://pethome.ir','pet',FALSE,'unknown','manual'),
('پت‌زون','petzone','petzone.ir','https://petzone.ir','pet',FALSE,'unknown','manual'),
('لوازم حیوانات خانگی','pettools','pettools.ir','https://pettools.ir','pet',FALSE,'unknown','manual'),
('دیجی زرگر','digizargar2','digizargar.com','https://digizargar.com','jewelry-gold',FALSE,'unknown','manual'),
('طلاسی','talasea','talasea.ir','https://talasea.ir','jewelry-gold',FALSE,'unknown','manual'),
('گلدینو','goldino','goldino.ir','https://goldino.ir','jewelry-gold',FALSE,'unknown','manual'),
('طلاپ','talapp','talapp.ir','https://talapp.ir','jewelry-gold',FALSE,'unknown','manual'),
('جواهری حقانی','haghighi-jewelry','haghighijewelry.com','https://haghighijewelry.com','jewelry-gold',FALSE,'unknown','manual'),
('نورنگار','noornegar3','noornegar.com','https://noornegar.com','audio-video',FALSE,'unknown','manual')
ON CONFLICT(domain) DO NOTHING;
INSERT INTO schema_migrations(version) VALUES ('041_market_store_registry_wave4') ON CONFLICT(version) DO NOTHING;
COMMIT;