import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import { ensurePlatformUser, requireAuth, type AuthClaims } from '../auth.js';
import { hasPermission } from '../permissions.js';
type RequestWithAuth=FastifyRequest&{auth:AuthClaims};
const deny=(reply:{code:(n:number)=>{send:(v:unknown)=>unknown}})=>reply.code(403).send({error:'forbidden'});
async function allowed(pool:Pool,req:RequestWithAuth,permission:string){return hasPermission(pool,req.auth,permission);}
async function audit(pool:Pool,req:RequestWithAuth,action:string,type:string,id:string|null,reason:string,metadata:unknown={}){await pool.query('INSERT INTO audit_logs(identity_id,actor_type,actor_identity_id,action,resource_type,resource_id,reason,metadata) VALUES($1,\'admin\',$1,$2,$3,$4,$5,$6)',[req.auth.sub,action,type,id,reason,metadata]);}
export function registerAdminRoutes(app:FastifyInstance,pool:Pool){
app.get('/internal/v1/admin/overview',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'users.read')))return deny(reply);const [u,t,n,a]=await Promise.all([pool.query('SELECT COUNT(*)::int count FROM platform_users'),pool.query("SELECT COUNT(*)::int count FROM support_tickets WHERE status NOT IN ('resolved','closed')"),pool.query("SELECT COUNT(*)::int count FROM news_articles WHERE status='published'"),pool.query("SELECT COUNT(*)::int count FROM ai_execution_runs WHERE status IN ('queued','running')")]);return{users:u.rows[0].count,openTickets:t.rows[0].count,publishedNews:n.rows[0].count,activeAiJobs:a.rows[0].count};});
app.get('/internal/v1/admin/users/:identityId',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'users.read')))return deny(reply);const identityId=(request.params as {identityId:string}).identityId;const u=await pool.query('SELECT id,identity_id,email,display_name,role,status,created_at,updated_at FROM platform_users WHERE identity_id=$1',[identityId]);if(!u.rows[0])return reply.code(404).send({error:'user_not_found'});const[t,ac,au]=await Promise.all([pool.query('SELECT * FROM support_tickets WHERE user_id=$1 ORDER BY updated_at DESC LIMIT 100',[u.rows[0].id]),pool.query('SELECT * FROM user_activity_events WHERE identity_id=$1 ORDER BY occurred_at DESC LIMIT 200',[identityId]),pool.query('SELECT * FROM audit_logs WHERE identity_id=$1 OR actor_identity_id=$1 ORDER BY created_at DESC LIMIT 200',[identityId])]);return{user:u.rows[0],tickets:t.rows,activity:ac.rows,audit:au.rows};});
app.get('/internal/v1/admin/news',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'content.read')))return deny(reply);const r=await pool.query('SELECT id,title,slug,status,published_at,created_at,updated_at FROM news_articles ORDER BY created_at DESC LIMIT 200');return{articles:r.rows};});
app.patch('/internal/v1/admin/news/:id/status',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'content.write')))return deny(reply);const b=(request.body??{}) as {status?:string};if(!['draft','published','archived'].includes(b.status??''))return reply.code(400).send({error:'invalid_status'});const id=(request.params as {id:string}).id;const r=await pool.query("UPDATE news_articles SET status=$1,published_at=CASE WHEN $1='published' THEN COALESCE(published_at,NOW()) ELSE published_at END,updated_at=NOW() WHERE id=$2 RETURNING *",[b.status,id]);if(!r.rows[0])return reply.code(404).send({error:'news_not_found'});await audit(pool,req,'news_status_change','news_article',id,'Admin content moderation',{status:b.status});return{article:r.rows[0]};});
app.delete('/internal/v1/admin/news/:id',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'content.delete')))return deny(reply);const id=(request.params as {id:string}).id;const r=await pool.query('DELETE FROM news_articles WHERE id=$1 RETURNING id,title,slug',[id]);if(!r.rows[0])return reply.code(404).send({error:'news_not_found'});await audit(pool,req,'delete','news_article',id,'Admin permanently deleted article',{title:r.rows[0].title});return{deleted:true,article:r.rows[0]};});
app.get('/internal/v1/admin/maintenance',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'maintenance.write')))return deny(reply);const r=await pool.query('SELECT * FROM maintenance_announcements ORDER BY created_at DESC LIMIT 50');return{announcements:r.rows};});
app.post('/internal/v1/admin/maintenance',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'maintenance.write')))return deny(reply);const b=(request.body??{}) as {title?:string;message?:string;severity?:string;endsAt?:string|null;showOnWeb?:boolean;showOnMobile?:boolean;dismissible?:boolean};if(!b.title?.trim()||!b.message?.trim())return reply.code(400).send({error:'title_and_message_required'});if(!['info','warning','critical'].includes(b.severity??'info'))return reply.code(400).send({error:'invalid_severity'});const adminId=await ensurePlatformUser(pool,req.auth);await pool.query('UPDATE maintenance_announcements SET is_active=FALSE,updated_at=NOW() WHERE is_active=TRUE');const x=await pool.query('INSERT INTO maintenance_announcements(title,message,severity,ends_at,show_on_web,show_on_mobile,dismissible,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[b.title.trim(),b.message.trim(),b.severity??'info',b.endsAt??null,b.showOnWeb!==false,b.showOnMobile!==false,b.dismissible===true,adminId]);await audit(pool,req,'publish_maintenance','maintenance_announcement',String(x.rows[0].id),'Global maintenance/announcement published');return reply.code(201).send({announcement:x.rows[0]});});
app.patch('/internal/v1/admin/maintenance/:id',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'maintenance.write')))return deny(reply);const id=(request.params as {id:string}).id,b=(request.body??{}) as {title?:string;message?:string;severity?:string;endsAt?:string|null;isActive?:boolean;showOnWeb?:boolean;showOnMobile?:boolean;dismissible?:boolean};const r=await pool.query('UPDATE maintenance_announcements SET title=COALESCE($1,title),message=COALESCE($2,message),severity=COALESCE($3,severity),ends_at=$4,is_active=COALESCE($5,is_active),show_on_web=COALESCE($6,show_on_web),show_on_mobile=COALESCE($7,show_on_mobile),dismissible=COALESCE($8,dismissible),updated_at=NOW() WHERE id=$9 RETURNING *',[b.title?.trim()||null,b.message?.trim()||null,b.severity??null,b.endsAt??null,b.isActive,b.showOnWeb,b.showOnMobile,b.dismissible,id]);if(!r.rows[0])return reply.code(404).send({error:'announcement_not_found'});await audit(pool,req,'update_maintenance','maintenance_announcement',id,'Admin updated global announcement');return{announcement:r.rows[0]};});
app.delete('/internal/v1/admin/maintenance/:id',{preHandler:requireAuth},async(request,reply)=>{const req=request as RequestWithAuth;if(!(await allowed(pool,req,'maintenance.write')))return deny(reply);const id=(request.params as {id:string}).id;const r=await pool.query('UPDATE maintenance_announcements SET is_active=FALSE,updated_at=NOW() WHERE id=$1 RETURNING id',[id]);if(!r.rows[0])return reply.code(404).send({error:'announcement_not_found'});await audit(pool,req,'disable','maintenance_announcement',id,'Admin disabled announcement');return{disabled:true};});
app.get('/api/v1/maintenance',async()=>{const r=await pool.query("SELECT id,title,message,severity,starts_at,ends_at,show_on_web,show_on_mobile,dismissible FROM maintenance_announcements WHERE is_active=TRUE AND starts_at<=NOW() AND (ends_at IS NULL OR ends_at>NOW()) ORDER BY created_at DESC LIMIT 1");return{announcement:r.rows[0]??null};});
}
