import type {FastifyInstance,FastifyRequest} from 'fastify';import type {Pool} from 'pg';import {requireAuth} from '../auth.js';import type { AuthClaims } from '../auth.js';import {hasPermission} from '../permissions.js';
type R=FastifyRequest&{auth:AuthClaims};const r=(x:FastifyRequest)=>x as R;const deny=(p:any)=>p.code(403).send({error:'forbidden'});
async function audit(pool:Pool,a:R,action:string,type:string,id:string){await pool.query("INSERT INTO audit_logs(identity_id,actor_type,actor_identity_id,action,resource_type,resource_id) VALUES($1,'admin',$1,$2,$3,$4)",[a.auth.sub,action,type,id]);}
export function registerAdminEcosystemRoutes(app:FastifyInstance,pool:Pool){
 app.get('/api/v1/admin/banner',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.read')))return deny(reply);return{listings:(await pool.query('SELECT b.*,u.identity_id,u.email FROM banner_listings b JOIN platform_users u ON u.id=b.user_id ORDER BY b.created_at DESC LIMIT 500')).rows};});
 app.patch('/api/v1/admin/banner/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.write')))return deny(reply);const id=(req.params as any).id,b=(req.body??{}) as any;if(b.status&&!['draft','published','paused','sold','archived'].includes(b.status))return reply.code(400).send({error:'invalid_status'});const x=await pool.query('UPDATE banner_listings SET title=COALESCE($1,title),description=COALESCE($2,description),price=COALESCE($3,price),city=COALESCE($4,city),status=COALESCE($5,status),updated_at=NOW() WHERE id=$6 RETURNING *',[b.title?.trim()||null,b.description??null,b.price??null,b.city??null,b.status??null,id]);if(!x.rows[0])return reply.code(404).send({error:'listing_not_found'});await audit(pool,a,'admin_banner_update','banner',id);return{listing:x.rows[0]};});
 app.delete('/api/v1/admin/banner/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.write')))return deny(reply);const id=(req.params as any).id;const x=await pool.query("UPDATE banner_listings SET status='archived',updated_at=NOW() WHERE id=$1 RETURNING id",[id]);if(!x.rows[0])return reply.code(404).send({error:'listing_not_found'});await audit(pool,a,'admin_banner_delete','banner',id);return{deleted:true};});
 app.get('/api/v1/admin/market/products',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.read')))return deny(reply);return{products:(await pool.query('SELECT p.*,u.identity_id,u.email FROM market_products p LEFT JOIN platform_users u ON u.id=p.seller_user_id ORDER BY p.created_at DESC LIMIT 500')).rows};});
 app.patch('/api/v1/admin/market/products/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.write')))return deny(reply);const id=(req.params as any).id,b=(req.body??{}) as any;if(b.status&&!['draft','published','out_of_stock','archived'].includes(b.status))return reply.code(400).send({error:'invalid_status'});const x=await pool.query('UPDATE market_products SET title=COALESCE($1,title),description=COALESCE($2,description),status=COALESCE($3,status),updated_at=NOW() WHERE id=$4 RETURNING *',[b.title?.trim()||null,b.description??null,b.status??null,id]);if(!x.rows[0])return reply.code(404).send({error:'product_not_found'});await audit(pool,a,'admin_market_update','market_product',id);return{product:x.rows[0]};});
 app.delete('/api/v1/admin/market/products/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.write')))return deny(reply);const id=(req.params as any).id;const x=await pool.query("UPDATE market_products SET status='archived',updated_at=NOW() WHERE id=$1 RETURNING id",[id]);if(!x.rows[0])return reply.code(404).send({error:'product_not_found'});await audit(pool,a,'admin_market_delete','market_product',id);return{deleted:true};});
 app.get('/api/v1/admin/forum',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.read')))return deny(reply);const [t,p]=await Promise.all([pool.query('SELECT * FROM forum_threads ORDER BY updated_at DESC LIMIT 500'),pool.query('SELECT * FROM forum_posts ORDER BY created_at DESC LIMIT 1000')]);return{threads:t.rows,posts:p.rows};});
 app.patch('/api/v1/admin/forum/threads/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.moderate')))return deny(reply);const id=(req.params as any).id,b=(req.body??{}) as any;if(b.status&&!['open','closed','archived'].includes(b.status))return reply.code(400).send({error:'invalid_status'});const x=await pool.query('UPDATE forum_threads SET status=COALESCE($1,status),moderation_status=COALESCE($2,moderation_status),updated_at=NOW() WHERE id=$3 RETURNING *',[b.status??null,b.moderationStatus??null,id]);if(!x.rows[0])return reply.code(404).send({error:'thread_not_found'});await audit(pool,a,'admin_forum_update','forum_thread',id);return{thread:x.rows[0]};});
 app.patch('/api/v1/admin/forum/posts/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.moderate')))return deny(reply);const id=(req.params as any).id,b=(req.body??{}) as any;if(!['visible','hidden','deleted','blocked'].includes(b.moderationStatus??''))return reply.code(400).send({error:'invalid_moderation_status'});const x=await pool.query('UPDATE forum_posts SET moderation_status=$1 WHERE id=$2 RETURNING *',[b.moderationStatus,id]);if(!x.rows[0])return reply.code(404).send({error:'post_not_found'});await audit(pool,a,'admin_forum_moderate','forum_post',id);return{post:x.rows[0]};});
 app.get('/api/v1/admin/hoosh/requests',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'ai.runs.read')))return deny(reply);return{requests:(await pool.query('SELECT * FROM hoosh_requests ORDER BY created_at DESC LIMIT 500')).rows,usage:(await pool.query('SELECT provider,model,COUNT(*)::int requests,COALESCE(SUM(input_tokens),0)::text input_tokens,COALESCE(SUM(output_tokens),0)::text output_tokens,COALESCE(SUM(cost),0)::text cost FROM hoosh_usage GROUP BY provider,model ORDER BY requests DESC')).rows};});
  app.get('/api/v1/admin/market/stores',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.read')))return deny(reply);return{stores:(await pool.query('SELECT * FROM market_stores ORDER BY name')).rows};});
  app.patch('/api/v1/admin/market/stores/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.write')))return deny(reply);const id=Number((req.params as any).id),b=(req.body??{}) as any;if(!Number.isSafeInteger(id))return reply.code(400).send({error:'invalid_id'});if(b.iframeMode&&!['allowed','blocked','unknown'].includes(b.iframeMode))return reply.code(400).send({error:'invalid_iframe_mode'});const q=await pool.query('UPDATE market_stores SET name=COALESCE($1,name),homepage_url=COALESCE($2,homepage_url),iframe_mode=COALESCE($3,iframe_mode),feed_type=COALESCE($4,feed_type),feed_url=COALESCE($5,feed_url),active=COALESCE($6,active),updated_at=NOW() WHERE id=$7 RETURNING *',[b.name?.trim()||null,b.homepageUrl??null,b.iframeMode??null,b.feedType??null,b.feedUrl??null,typeof b.active==='boolean'?b.active:null,id]);if(!q.rows[0])return reply.code(404).send({error:'store_not_found'});await audit(pool,a,'admin_market_store_update','market_store',String(id));return{store:q.rows[0]};});
  app.get('/api/v1/admin/market/tickets',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.read')))return deny(reply);const status=String((req.query as any)?.status??'').trim();const p=status?await pool.query('SELECT t.*,u.identity_id,u.email FROM market_tickets t JOIN platform_users u ON u.id=t.user_id WHERE t.status=$1 ORDER BY t.updated_at DESC LIMIT 500',[status]):await pool.query('SELECT t.*,u.identity_id,u.email FROM market_tickets t JOIN platform_users u ON u.id=t.user_id ORDER BY t.updated_at DESC LIMIT 500');return{tickets:p.rows};});
  app.get('/api/v1/admin/market/tickets/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.read')))return deny(reply);const id=Number((req.params as any).id);const t=await pool.query('SELECT t.*,u.identity_id,u.email FROM market_tickets t JOIN platform_users u ON u.id=t.user_id WHERE t.id=$1',[id]);if(!t.rows[0])return reply.code(404).send({error:'ticket_not_found'});return{ticket:t.rows[0],messages:(await pool.query('SELECT * FROM market_ticket_messages WHERE ticket_id=$1 ORDER BY created_at',[id])).rows};});
  app.post('/api/v1/admin/market/tickets/:id/reply',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.write')))return deny(reply);const id=Number((req.params as any).id),b=(req.body??{}) as any;if(typeof b.message!=='string'||!b.message.trim()||b.message.length>10000)return reply.code(400).send({error:'message_required'});const q=await pool.query('INSERT INTO market_ticket_messages(ticket_id,author_identity_id,author_type,message) VALUES($1,$2,\'admin\',$3) RETURNING *',[id,a.auth.sub,b.message.trim()]);await pool.query('UPDATE market_tickets SET status=\'answered\',updated_at=NOW() WHERE id=$1',[id]);await audit(pool,a,'admin_market_ticket_reply','market_ticket',String(id));return{message:q.rows[0]};});
  app.patch('/api/v1/admin/market/tickets/:id',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.write')))return deny(reply);const id=Number((req.params as any).id),b=(req.body??{}) as any;if(b.status&&!['open','pending','answered','closed'].includes(b.status))return reply.code(400).send({error:'invalid_status'});if(b.priority&&!['low','normal','high','urgent'].includes(b.priority))return reply.code(400).send({error:'invalid_priority'});const q=await pool.query('UPDATE market_tickets SET status=COALESCE($1,status),priority=COALESCE($2,priority),updated_at=NOW() WHERE id=$3 RETURNING *',[b.status??null,b.priority??null,id]);if(!q.rows[0])return reply.code(404).send({error:'ticket_not_found'});await audit(pool,a,'admin_market_ticket_update','market_ticket',String(id));return{ticket:q.rows[0]};});
  app.get('/api/v1/admin/market/events',{preHandler:requireAuth},async(req,reply)=>{const a=r(req);if(!(await hasPermission(pool,a.auth,'content.read')))return deny(reply);return{events:(await pool.query('SELECT * FROM market_user_events ORDER BY created_at DESC LIMIT 1000')).rows};});
}
