import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {Pool} from 'pg';
import {randomUUID} from 'node:crypto';
import {ensurePlatformUser,requireAuth,type AuthClaims} from '../auth.js';
type R=FastifyRequest&{auth:AuthClaims};
const auth=(r:FastifyRequest)=>r as R;
const page=(q:any)=>{const p=Math.max(1,Number(q.page)||1),l=Math.min(100,Math.max(1,Number(q.limit)||20));return[p,l,(p-1)*l]};

export function registerEcosystemRoutes(app:FastifyInstance,pool:Pool){
 // Banner: listing lifecycle, media, favorites and buyer inquiries.
 app.get('/api/v1/banner/:id',async(req,reply)=>{const id=Number((req.params as any).id);if(!Number.isSafeInteger(id))return reply.code(400).send({error:'invalid_id'});const [l,m]=await Promise.all([pool.query('SELECT * FROM banner_listings WHERE id=$1 AND status<>$2',[id,'archived']),pool.query('SELECT id,url,media_type,sort_order FROM banner_media WHERE listing_id=$1 ORDER BY sort_order,id',[id])]);if(!l.rows[0])return reply.code(404).send({error:'listing_not_found'});return{listing:l.rows[0],media:m.rows};});
 app.get('/api/v1/banner/me',{preHandler:requireAuth},async(req)=>{const r=auth(req);const uid=await ensurePlatformUser(pool,r.auth);return{listings:(await pool.query('SELECT * FROM banner_listings WHERE user_id=$1 ORDER BY created_at DESC',[uid])).rows};});
 app.patch('/api/v1/banner/:id',{preHandler:requireAuth},async(req,reply)=>{const r=auth(req),id=Number((req.params as any).id),b=(req.body??{}) as any;if(!Number.isSafeInteger(id))return reply.code(400).send({error:'invalid_id'});const uid=await ensurePlatformUser(pool,r.auth);const x=await pool.query('UPDATE banner_listings SET title=COALESCE($1,title),description=COALESCE($2,description),price=COALESCE($3,price),currency=COALESCE($4,currency),city=COALESCE($5,city),category_id=COALESCE($6,category_id),status=COALESCE($7,status),updated_at=NOW() WHERE id=$8 AND user_id=$9 RETURNING *',[b.title?.trim()||null,b.description??null,b.price??null,b.currency?.toUpperCase()??null,b.city??null,b.categoryId??null,b.status??null,id,uid]);if(!x.rows[0])return reply.code(404).send({error:'listing_not_found'});return{listing:x.rows[0]};});
 app.delete('/api/v1/banner/:id',{preHandler:requireAuth},async(req,reply)=>{const r=auth(req),id=Number((req.params as any).id),uid=await ensurePlatformUser(pool,r.auth);const x=await pool.query("UPDATE banner_listings SET status='archived',updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING id",[id,uid]);if(!x.rows[0])return reply.code(404).send({error:'listing_not_found'});return{deleted:true};});
 app.post('/api/v1/banner/:id/favorite',{preHandler:requireAuth},async(req,reply)=>{const uid=await ensurePlatformUser(pool,auth(req).auth),id=Number((req.params as any).id);try{await pool.query('INSERT INTO banner_favorites(user_id,listing_id) VALUES($1,$2)',[uid,id]);return{favorite:true};}catch(e:any){if(e?.code==='23505'){await pool.query('DELETE FROM banner_favorites WHERE user_id=$1 AND listing_id=$2',[uid,id]);return{favorite:false};}throw e;}});
 app.post('/api/v1/banner/:id/inquiries',{preHandler:requireAuth},async(req,reply)=>{const uid=await ensurePlatformUser(pool,auth(req).auth),id=Number((req.params as any).id),body=(req.body as any)?.message;if(typeof body!=='string'||!body.trim())return reply.code(400).send({error:'message_required'});const x=await pool.query('INSERT INTO banner_inquiries(listing_id,buyer_user_id,message) VALUES($1,$2,$3) RETURNING *',[id,uid,body.trim()]);return reply.code(201).send({inquiry:x.rows[0]});});

 // Market: product detail, seller offers, favorites and order lifecycle.
 app.get('/api/v1/market/products/:id',async(req,reply)=>{const id=Number((req.params as any).id);const p=await pool.query("SELECT * FROM market_products WHERE id=$1 AND status<>'archived'",[id]);if(!p.rows[0])return reply.code(404).send({error:'product_not_found'});const [m,o]=await Promise.all([pool.query('SELECT id,url,sort_order FROM market_media WHERE product_id=$1 ORDER BY sort_order,id',[id]),pool.query('SELECT o.id,o.seller_name,o.seller_url,o.price,o.currency,o.availability,o.shipping_cost,o.updated_at,o.store_id,o.external_product_id,o.product_url,o.image_url,s.name store_name,s.domain store_domain,s.iframe_mode FROM market_offers o LEFT JOIN market_stores s ON s.id=o.store_id WHERE o.product_id=$1 ORDER BY o.price,o.id',[id])]);return{product:p.rows[0],media:m.rows,offers:o.rows};});
 app.get('/api/v1/market/me/orders',{preHandler:requireAuth},async(req)=>{const uid=await ensurePlatformUser(pool,auth(req).auth);return{orders:(await pool.query('SELECT * FROM market_orders WHERE user_id=$1 ORDER BY created_at DESC LIMIT 200',[uid])).rows};});
 app.post('/api/v1/market/products/:id/order',{preHandler:requireAuth},async(req,reply)=>{const uid=await ensurePlatformUser(pool,auth(req).auth),id=Number((req.params as any).id),b=(req.body??{}) as any;const offerId=Number(b.offerId),idempotencyKey=typeof b.idempotencyKey==='string'?b.idempotencyKey.trim():'';if(!Number.isSafeInteger(id)||id<=0||!Number.isSafeInteger(offerId)||offerId<=0||typeof b.quantity!=='string'||!/^(?:0|[1-9]\d{0,11})(?:\.\d{1,6})?$/.test(b.quantity)||b.quantity==='0'||Number(b.quantity)>1000000||typeof b.unitPrice!=='string'||!/^(?:0|[1-9]\d{0,19})(?:\.\d{1,8})?$/.test(b.unitPrice)||typeof b.currency!=='string'||!/^[A-Z]{3}$/.test(b.currency)||idempotencyKey.length<8||idempotencyKey.length>200)return reply.code(400).send({error:'invalid_order'});const currency=b.currency.toUpperCase();const operationId=randomUUID();const fingerprint=JSON.stringify({productId:id,offerId,quantity:String(b.quantity),unitPrice:String(b.unitPrice),currency});try{const x=await pool.query('INSERT INTO market_orders(user_id,product_id,offer_id,quantity,unit_price,currency,idempotency_key,operation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[uid,id,offerId,b.quantity,b.unitPrice,currency,idempotencyKey,operationId]);return reply.code(201).send({order:x.rows[0],operationId});}catch(e:any){if(e?.code==='23505'){const existing=await pool.query('SELECT * FROM market_orders WHERE user_id=$1 AND idempotency_key=$2',[uid,idempotencyKey]);if(existing.rows[0]){const existingFingerprint=JSON.stringify({productId:existing.rows[0].product_id,offerId:existing.rows[0].offer_id,quantity:String(existing.rows[0].quantity),unitPrice:String(existing.rows[0].unit_price),currency:existing.rows[0].currency});if(existingFingerprint!==fingerprint)return reply.code(409).send({error:'idempotency_key_reused'});return{order:existing.rows[0],operationId:existing.rows[0].operation_id??null,idempotent:true};}}if(typeof e?.message==='string'&&e.message.startsWith('market_'))return reply.code(409).send({error:e.message});throw e;}});
 app.post('/api/v1/market/products/:id/favorite',{preHandler:requireAuth},async(req)=>{const uid=await ensurePlatformUser(pool,auth(req).auth),id=Number((req.params as any).id);try{await pool.query('INSERT INTO market_favorites(user_id,product_id) VALUES($1,$2)',[uid,id]);return{favorite:true};}catch(e:any){if(e?.code==='23505'){await pool.query('DELETE FROM market_favorites WHERE user_id=$1 AND product_id=$2',[uid,id]);return{favorite:false};}throw e;}});

 // An Hoosh: conversation/message/usage records. Provider execution is intentionally behind a later gateway.
 app.get('/api/v1/hoosh/conversations',{preHandler:requireAuth},async(req)=>{const uid=auth(req).auth.sub;return{conversations:(await pool.query('SELECT id,title,model,status,created_at,updated_at FROM hoosh_conversations WHERE identity_id=$1 AND status<>$2 ORDER BY updated_at DESC',[uid,'blocked'])).rows};});
 app.post('/api/v1/hoosh/conversations',{preHandler:requireAuth},async(req,reply)=>{const uid=auth(req).auth.sub,b=(req.body??{}) as any;const x=await pool.query('INSERT INTO hoosh_conversations(identity_id,title,model) VALUES($1,$2,$3) RETURNING *',[uid,b.title?.trim()||'گفتگوی جدید',b.model??null]);return reply.code(201).send({conversation:x.rows[0]});});
 app.get('/api/v1/hoosh/conversations/:id/messages',{preHandler:requireAuth},async(req,reply)=>{const uid=auth(req).auth.sub,id=Number((req.params as any).id);const c=await pool.query('SELECT id FROM hoosh_conversations WHERE id=$1 AND identity_id=$2',[id,uid]);if(!c.rows[0])return reply.code(404).send({error:'conversation_not_found'});return{messages:(await pool.query('SELECT id,role,content,metadata,created_at FROM hoosh_messages WHERE conversation_id=$1 ORDER BY created_at',[id])).rows};});
 app.post('/api/v1/hoosh/conversations/:id/messages',{preHandler:requireAuth},async(req,reply)=>{const uid=auth(req).auth.sub,id=Number((req.params as any).id),b=(req.body??{}) as any;if(typeof b.content!=='string'||!b.content.trim()||b.content.length>20000)return reply.code(400).send({error:'invalid_message'});const c=await pool.query('SELECT id FROM hoosh_conversations WHERE id=$1 AND identity_id=$2 AND status=\'active\'',[id,uid]);if(!c.rows[0])return reply.code(404).send({error:'conversation_not_found'});const q=await pool.query('INSERT INTO hoosh_requests(identity_id,conversation_id,request_text,status,model) VALUES($1,$2,$3,\'queued\',$4) RETURNING *',[uid,id,b.content.trim(),b.model??null]);await pool.query('INSERT INTO hoosh_messages(conversation_id,role,content) VALUES($1,\'user\',$2)',[id,b.content.trim()]);return reply.code(202).send({request:q.rows[0],status:'queued'});});
 app.get('/api/v1/hoosh/usage',{preHandler:requireAuth},async(req)=>{const uid=auth(req).auth.sub;const [u,r]=await Promise.all([pool.query('SELECT COALESCE(SUM(input_tokens),0)::text input_tokens,COALESCE(SUM(output_tokens),0)::text output_tokens,COALESCE(SUM(cost),0)::text cost FROM hoosh_usage WHERE identity_id=$1',[uid]),pool.query('SELECT * FROM hoosh_requests WHERE identity_id=$1 ORDER BY created_at DESC LIMIT 100',[uid])]);return{usage:u.rows[0],requests:r.rows};});

 // Financial Center: personal income/expense records and budgets.
 app.get('/api/v1/financial-center/entries',{preHandler:requireAuth},async(req)=>{const uid=auth(req).auth.sub,[p,l,o]=page(req.query);const r=await pool.query('SELECT * FROM financial_entries WHERE identity_id=$1 ORDER BY occurred_at DESC LIMIT $2 OFFSET $3',[uid,l,o]);return{items:r.rows,pagination:{page:p,limit:l}};});
 app.post('/api/v1/financial-center/entries',{preHandler:requireAuth},async(req,reply)=>{const uid=auth(req).auth.sub,b=(req.body??{}) as any;if(!['income','expense'].includes(b.type)||typeof b.amount!=='string'||!/^(?:0|[1-9]\d{0,19})(?:\.\d{1,8})?$/.test(b.amount)||b.amount==='0'||typeof b.currency!=='string'||!/^[A-Z]{3}$/.test(b.currency))return reply.code(400).send({error:'invalid_entry'});const r=await pool.query('INSERT INTO financial_entries(identity_id,category_id,type,amount,currency,description,source,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,NOW())) RETURNING *',[uid,b.categoryId??null,b.type,b.amount,b.currency,b.description?.trim()??null,b.source?.trim()??'manual',b.occurredAt??null]);return reply.code(201).send({entry:r.rows[0]});});
 app.delete('/api/v1/financial-center/entries/:id',{preHandler:requireAuth},async(req,reply)=>{const uid=auth(req).auth.sub,id=Number((req.params as any).id);const r=await pool.query('DELETE FROM financial_entries WHERE id=$1 AND identity_id=$2 RETURNING id',[id,uid]);if(!r.rows[0])return reply.code(404).send({error:'entry_not_found'});return{deleted:true};});
 app.get('/api/v1/financial-center/summary',{preHandler:requireAuth},async(req)=>{const uid=auth(req).auth.sub;const r=await pool.query("SELECT currency,COALESCE(SUM(amount) FILTER(WHERE type='income'),0)::text income,COALESCE(SUM(amount) FILTER(WHERE type='expense'),0)::text expense FROM financial_entries WHERE identity_id=$1 GROUP BY currency ORDER BY currency",[uid]);return{summary:r.rows};});
}
