import type {FastifyInstance,FastifyRequest} from 'fastify';import type {Pool} from 'pg';import {requireAuth,type AuthClaims} from '../auth.js';import {hasPermission} from '../permissions.js';
type R=FastifyRequest&{auth:AuthClaims};const deny=(p:any)=>p.code(403).send({error:'forbidden'});
export function registerOperationsRoutes(app:FastifyInstance,pool:Pool){
 app.post('/internal/v1/admin/approvals',{preHandler:requireAuth},async(req,reply)=>{const a=req as R;if(!(await hasPermission(pool,a.auth,'approvals.write')))return deny(reply);const b=(req.body??{}) as any;if(!b.action||!b.resourceType||!b.resourceId)return reply.code(400).send({error:'invalid_approval'});const x=await pool.query('INSERT INTO approval_requests(requester_identity_id,requester_service,action,resource_type,resource_id,payload,risk_level) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[a.auth.sub,b.requesterService??'platform',b.action,b.resourceType,String(b.resourceId),b.payload??{},['low','normal','high','critical'].includes(b.riskLevel)?b.riskLevel:'normal']);return reply.code(201).send({approval:x.rows[0]});});
 app.get('/internal/v1/admin/approvals',{preHandler:requireAuth},async(req,reply)=>{const a=req as R;if(!(await hasPermission(pool,a.auth,'approvals.read')))return deny(reply);const q=req.query as any;const x=await pool.query('SELECT * FROM approval_requests WHERE ($1::text IS NULL OR status=$1) ORDER BY created_at DESC LIMIT 500',[q.status??null]);return{approvals:x.rows};});
 app.patch('/internal/v1/admin/approvals/:id',{preHandler:requireAuth},async(req,reply)=>{const a=req as R;if(!(await hasPermission(pool,a.auth,'approvals.write')))return deny(reply);const b=(req.body??{}) as any;if(!['approved','rejected','cancelled'].includes(b.status))return reply.code(400).send({error:'invalid_decision'});const id=(req.params as any).id;const pending=await pool.query('SELECT requester_identity_id FROM approval_requests WHERE id=$1 AND status=\'pending\'',[id]);if(!pending.rows[0])return reply.code(404).send({error:'approval_not_found'});if(pending.rows[0].requester_identity_id===a.auth.sub)return reply.code(409).send({error:'self_approval_forbidden'});const x=await pool.query('UPDATE approval_requests SET status=$1,approver_identity_id=$2,decision_reason=$3,decided_at=NOW() WHERE id=$4 AND status=\'pending\' RETURNING *',[b.status,a.auth.sub,b.reason?.trim()??null,id]);if(!x.rows[0])return reply.code(409).send({error:'approval_already_decided'});await pool.query("INSERT INTO audit_logs(identity_id,actor_type,actor_identity_id,action,resource_type,resource_id,reason) VALUES($1,'admin',$1,'approval_decision','approval_request',$2,$3)",[a.auth.sub,id,b.reason?.trim()??null]);return{approval:x.rows[0]};});
 app.get('/internal/v1/admin/service-health',{preHandler:requireAuth},async(req,reply)=>{const a=req as R;if(!(await hasPermission(pool,a.auth,'service_health.read')))return deny(reply);const x=await pool.query('SELECT DISTINCT ON(service) service,status,version,latency_ms,details,checked_at FROM service_health_snapshots ORDER BY service,checked_at DESC');return{services:x.rows};});
 app.post('/internal/v1/admin/reconciliation-runs',{preHandler:requireAuth},async(req,reply)=>{const a=req as R;if(!(await hasPermission(pool,a.auth,'reconciliation.write')))return deny(reply);const b=(req.body??{}) as any;if(!b.service||!b.scope)return reply.code(400).send({error:'service_and_scope_required'});const x=await pool.query('INSERT INTO reconciliation_runs(service,scope) VALUES($1,$2) RETURNING *',[b.service,b.scope]);return reply.code(201).send({run:x.rows[0]});});
 app.get('/internal/v1/admin/reconciliation-runs',{preHandler:requireAuth},async(req,reply)=>{const a=req as R;if(!(await hasPermission(pool,a.auth,'reconciliation.read')))return deny(reply);return{runs:(await pool.query('SELECT * FROM reconciliation_runs ORDER BY started_at DESC LIMIT 200')).rows};});
}
