import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {Pool} from 'pg';
import {ensurePlatformUser,requireAuth,type AuthClaims} from '../auth.js';
type R=FastifyRequest&{auth:AuthClaims};
const adminOnly=async(req:FastifyRequest,reply:any)=>{const role=(req as R).auth.role;if(!['admin','super_admin','operator'].includes(role)){reply.code(403).send({error:'forbidden'});return false;}return true;};
export function registerSupportRoutes(app:FastifyInstance,pool:Pool){
app.get('/api/v1/support/tickets',{preHandler:requireAuth},async(req)=>{const userId=await ensurePlatformUser(pool,(req as R).auth);return{tickets:(await pool.query('SELECT id,subject,status,priority,created_at,updated_at,closed_at FROM support_tickets WHERE user_id=$1 ORDER BY updated_at DESC LIMIT 100',[userId])).rows};});
app.post('/api/v1/support/tickets',{preHandler:requireAuth},async(req,reply)=>{const userId=await ensurePlatformUser(pool,(req as R).auth);const b=(req.body??{}) as any,subject=String(b.subject??'').trim(),message=String(b.message??'').trim();if(subject.length<3||subject.length>200||!message||message.length>10000)return reply.code(400).send({error:'invalid_ticket'});const client=await pool.connect();try{await client.query('BEGIN');const t=(await client.query('INSERT INTO support_tickets(user_id,subject) VALUES($1,$2) RETURNING id,subject,status,priority,created_at,updated_at',[userId,subject])).rows[0];await client.query("INSERT INTO support_ticket_messages(ticket_id,sender_user_id,sender_role,message) VALUES($1,$2,'user',$3)",[t.id,userId,message]);await client.query('COMMIT');return reply.code(201).send({ticket:t});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
app.get('/api/v1/support/tickets/:id',{preHandler:requireAuth},async(req,reply)=>{const userId=await ensurePlatformUser(pool,(req as R).auth),id=Number((req.params as any).id),t=(await pool.query('SELECT id,subject,status,priority,created_at,updated_at,closed_at FROM support_tickets WHERE id=$1 AND user_id=$2',[id,userId])).rows[0];if(!t)return reply.code(404).send({error:'ticket_not_found'});return{ticket:t,messages:(await pool.query('SELECT id,sender_role,message,created_at FROM support_ticket_messages WHERE ticket_id=$1 ORDER BY created_at',[id])).rows};});
app.post('/api/v1/support/tickets/:id/messages',{preHandler:requireAuth},async(req,reply)=>{const userId=await ensurePlatformUser(pool,(req as R).auth),id=Number((req.params as any).id),message=String((req.body as any)?.message??'').trim();if(!message||message.length>10000)return reply.code(400).send({error:'invalid_message'});const exists=(await pool.query("SELECT id FROM support_tickets WHERE id=$1 AND user_id=$2 AND status<>'closed'",[id,userId])).rows[0];if(!exists)return reply.code(404).send({error:'ticket_not_found'});await pool.query("INSERT INTO support_ticket_messages(ticket_id,sender_user_id,sender_role,message) VALUES($1,$2,'user',$3)",[id,userId,message]);await pool.query("UPDATE support_tickets SET status='open',updated_at=NOW() WHERE id=$1",[id]);return{ok:true};});
app.get('/api/v1/admin/support/tickets',{preHandler:requireAuth},async(req,reply)=>{if(!await adminOnly(req,reply))return;return{tickets:(await pool.query('SELECT t.id,t.subject,t.status,t.priority,t.created_at,t.updated_at,t.closed_at,u.email,u.display_name FROM support_tickets t JOIN platform_users u ON u.id=t.user_id ORDER BY t.updated_at DESC LIMIT 500')).rows};});
app.post('/api/v1/admin/support/tickets/:id/reply',{preHandler:requireAuth},async(req,reply)=>{if(!await adminOnly(req,reply))return;const id=Number((req.params as any).id),message=String((req.body as any)?.message??'').trim();if(!message||message.length>10000)return reply.code(400).send({error:'invalid_message'});const sender=await ensurePlatformUser(pool,(req as R).auth);const exists=(await pool.query('SELECT id FROM support_tickets WHERE id=$1',[id])).rows[0];if(!exists)return reply.code(404).send({error:'ticket_not_found'});await pool.query('INSERT INTO support_ticket_messages(ticket_id,sender_user_id,sender_role,message) VALUES($1,$2,$3,$4)',[id,sender,(req as R).auth.role==='operator'?'operator':'admin',message]);await pool.query("UPDATE support_tickets SET status='answered',updated_at=NOW() WHERE id=$1",[id]);return{ok:true};});
}