CREATE TABLE IF NOT EXISTS schema_migrations(version TEXT PRIMARY KEY,applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS financial_users(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,identity_id UUID NOT NULL UNIQUE,email TEXT,display_name TEXT,role TEXT NOT NULL DEFAULT 'user',status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS financial_accounts(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,currency CHAR(3) NOT NULL DEFAULT 'IRR',provider_account_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS financial_cards(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES financial_users(id) ON DELETE CASCADE,account_id BIGINT NOT NULL REFERENCES financial_accounts(id) ON DELETE CASCADE,last4 CHAR(4) NOT NULL,bank_name TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_financial_cards_user ON financial_cards(customer_id,status);
CREATE TABLE IF NOT EXISTS financial_finnotech_oauth_states(state TEXT PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES financial_users(id) ON DELETE CASCADE,redirect_uri TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS financial_finnotech_connections(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES financial_users(id) ON DELETE CASCADE,provider TEXT NOT NULL DEFAULT 'FINNOTECH',client_id TEXT,bank_code TEXT,provider_account_id TEXT,provider_subject TEXT,access_token_enc TEXT,refresh_token_enc TEXT,access_token_expires_at TIMESTAMPTZ,scope TEXT,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','expired','revoked','error')),last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(customer_id,provider,bank_code));
CREATE TABLE IF NOT EXISTS financial_card_audit_permissions(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES financial_users(id) ON DELETE CASCADE,card_id BIGINT NOT NULL REFERENCES financial_cards(id) ON DELETE CASCADE,enabled BOOLEAN NOT NULL DEFAULT FALSE,enabled_at TIMESTAMPTZ,disabled_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(customer_id,card_id));
CREATE TABLE IF NOT EXISTS financial_card_transactions(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES financial_users(id) ON DELETE CASCADE,card_id BIGINT NOT NULL REFERENCES financial_cards(id) ON DELETE CASCADE,external_id TEXT NOT NULL,direction TEXT NOT NULL CHECK(direction IN ('income','expense','internal')),amount NUMERIC(24,8) NOT NULL CHECK(amount>0),currency CHAR(3) NOT NULL,description TEXT,category TEXT,occurred_at TIMESTAMPTZ NOT NULL,source TEXT NOT NULL CHECK(source IN ('FINNOTECH','ANPARDAZ')),raw_metadata JSONB NOT NULL DEFAULT '{}',accounting_status TEXT NOT NULL DEFAULT 'pending' CHECK(accounting_status IN ('pending','posted','failed')),accounting_reference TEXT,accounting_error TEXT,accounting_updated_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(card_id,external_id));
CREATE INDEX IF NOT EXISTS idx_financial_card_tx_user_date ON financial_card_transactions(customer_id,occurred_at DESC);
CREATE TABLE IF NOT EXISTS financial_notifications(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES financial_users(id) ON DELETE CASCADE,card_id BIGINT REFERENCES financial_cards(id) ON DELETE SET NULL,transaction_id BIGINT REFERENCES financial_card_transactions(id) ON DELETE SET NULL,type TEXT NOT NULL CHECK(type IN ('sync','large_transaction','warning')),title TEXT NOT NULL,body TEXT NOT NULL,metadata JSONB NOT NULL DEFAULT '{}',read_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_financial_notifications_user_date ON financial_notifications(customer_id,created_at DESC);
CREATE OR REPLACE VIEW financial_daily_summary AS SELECT t.customer_id,t.card_id,MAX(c.last4) AS card_last4,MAX(c.bank_name) AS bank_name,(t.occurred_at AT TIME ZONE 'Asia/Tehran')::date AS local_day,t.direction,COALESCE(t.category,'سایر') AS category,t.currency,SUM(t.amount) AS total,COUNT(*)::bigint AS transaction_count FROM financial_card_transactions t JOIN financial_cards c ON c.id=t.card_id GROUP BY t.customer_id,t.card_id,(t.occurred_at AT TIME ZONE 'Asia/Tehran')::date,t.direction,COALESCE(t.category,'سایر'),t.currency;

INSERT INTO schema_migrations(version) VALUES ('001_financial_center_schema') ON CONFLICT(version) DO NOTHING;
