import type {FastifyInstance,FastifyRequest,FastifyReply} from 'fastify';
import type {Pool} from 'pg';
import {requireAuth,type AuthClaims} from '../auth.js';import {hasPermission} from '../permissions.js';

type R=FastifyRequest&{auth:AuthClaims};const r=(x:FastifyRequest)=>x as R;
const deny=(p:FastifyReply)=>p.code(403).send({error:'forbidden'});

export function registerMarketDataRoutes(app:FastifyInstance,pool:Pool){
 app.get<{Querystring:{symbol?:string}}>('/api/v1/market-data/quotes',async(req)=>{const symbol=req.query.symbol?.trim().toUpperCase();const params:any[]=[];const where=symbol?(params.push(symbol),'WHERE s.symbol=$1'):'';const q=await pool.query(`WITH latest AS (SELECT DISTINCT ON (o.symbol_id,o.source_id) o.symbol_id,o.source_id,o.bid,o.ask,o.last_price,o.volume_24h,o.received_at FROM market_data_observations o WHERE o.received_at>NOW()-INTERVAL '2 minutes' ORDER BY o.symbol_id,o.source_id,o.received_at DESC), usable AS (SELECT l.* FROM latest l JOIN market_data_health h ON h.source_id=l.source_id WHERE h.status IN ('healthy','degraded')), current AS (SELECT s.id,s.symbol,s.base_asset,s.quote_asset,percentile_cont(0.5) WITHIN GROUP (ORDER BY u.bid) FILTER(WHERE u.bid IS NOT NULL)::numeric(38,18)::text bid,percentile_cont(0.5) WITHIN GROUP (ORDER BY u.ask) FILTER(WHERE u.ask IS NOT NULL)::numeric(38,18)::text ask,percentile_cont(0.5) WITHIN GROUP (ORDER BY u.last_price) FILTER(WHERE u.last_price IS NOT NULL)::numeric(38,18)::text last_price,percentile_cont(0.5) WITHIN GROUP (ORDER BY u.volume_24h) FILTER(WHERE u.volume_24h IS NOT NULL)::numeric(38,18)::text volume_24h,MAX(u.received_at) received_at,COUNT(DISTINCT u.source_id)::int source_count FROM market_data_symbols s LEFT JOIN usable u ON u.symbol_id=s.id ${where} GROUP BY s.id,s.symbol,s.base_asset,s.quote_asset), baseline AS (SELECT s.id,percentile_cont(0.5) WITHIN GROUP (ORDER BY o.last_price) FILTER(WHERE o.last_price IS NOT NULL)::numeric(38,18) baseline_price FROM market_data_symbols s JOIN market_data_observations o ON o.symbol_id=s.id JOIN market_data_health h ON h.source_id=o.source_id AND h.status IN ('healthy','degraded') WHERE o.received_at BETWEEN NOW()-INTERVAL '26 hours' AND NOW()-INTERVAL '22 hours' GROUP BY s.id) SELECT c.symbol,c.base_asset,c.quote_asset,c.bid,c.ask,c.last_price,c.volume_24h,CASE WHEN b.baseline_price IS NOT NULL AND b.baseline_price>0 AND c.last_price IS NOT NULL THEN ((c.last_price::numeric-b.baseline_price)/b.baseline_price*100)::numeric(20,8)::text ELSE NULL END change24h,c.received_at,c.source_count FROM current c LEFT JOIN baseline b ON b.id=c.id ORDER BY c.symbol`,params);return{quotes:q.rows};});
 app.get('/api/v1/market-data/sources',{preHandler:requireAuth},async(req,reply)=>{if(!(await hasPermission(pool,r(req).auth,'service_health.read')))return deny(reply);return{sources:(await pool.query('SELECT s.*,h.status,h.last_success_at,h.last_failure_at,h.consecutive_failures,h.last_error FROM market_data_sources s LEFT JOIN market_data_health h ON h.source_id=s.id ORDER BY s.priority,s.name')).rows};});
 app.get('/api/v1/market-data/symbols',async()=>({symbols:(await pool.query('SELECT id,symbol,base_asset,quote_asset,enabled FROM market_data_symbols ORDER BY symbol')).rows}));
}
